### ISSUE TITLE
Clear notifications in notification shade after clicking mark all as read

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1005]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@tneot01` in `#requests`.

**Comment by zlshames** [comment]
Done. my beta branch

**Comment by CSab6482** [comment]
Has the latest beta been released? I am still fsvi g this bug on 1.3.0 rc1

https://user-images.githubusercontent.com/53708281/124397728-a476d100-dcdf-11eb-9ddc-fd4eafed8813.mp4
