### ISSUE TITLE
Clear notification from notif shade when long pressing chat on conversation details page

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1010]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@tneot01` in `#requests`.

**Comment by CSab6482** [comment]
Here is a screen recording of the issue

https://user-images.githubusercontent.com/53708281/124397728-a476d100-dcdf-11eb-9ddc-fd4eafed8813.mp4

**Comment by tneotia** [comment]
Done on nullsafety branch
