### ISSUE TITLE
[Flutter 2 Migration] Status bar color doesn't match background (for custom themes AKA Nord)

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1021]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#feedback`.

**Comment by CSab6482** [comment]
![Screenshot_20210706-150203](https://user-images.githubusercontent.com/53708281/124653450-4d056c00-de6b-11eb-8abf-ebd0c465ffb1.jpg)

**Comment by zlshames** [comment]
Either this was fixed, or i can't replicate on my virtual pixel device. Will need to test on my actual phone (OP7Pro)
