### ISSUE TITLE
[Flutter 2 Migration] Bottom Navigation Bar is always in light mode

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1024]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#feedback`.

**Comment by CSab6482** [comment]
![Screenshot_20210706-145852](https://user-images.githubusercontent.com/53708281/124653464-5262b680-de6b-11eb-99e1-678afe37f610.jpg)

**Comment by tneotia** [comment]
Confirmed fixed by @CSab6482
