### ISSUE TITLE
[Flutter 2 Migration] Tapping an attachment picker preview causes grey screen

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1032]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#android-bugs`.

**Comment by CSab6482** [comment]
https://user-images.githubusercontent.com/53708281/124799588-b7c5ae80-df22-11eb-9aa4-22cf7bee05d2.mp4

**Comment by tneotia** [comment]
Some sort of null exception happening. Nullsafety ftw

**Comment by zlshames** [comment]
Done
