### ISSUE TITLE
contact name duplicates/autofills in chat creator after selecting a contact

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1035]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@tneot01` in `#support`.

**Comment by zlshames** [comment]
I can't replicate this. Can anyone else confirm?

**Comment by tneotia** [comment]
Type an email that isn't a contact and see the behavior

**Comment by zlshames** [comment]
> Type an email that isn't a contact and see the behavior

Can you break down the steps? I typed test@test.com and hit enter, and it seemed to add it correctly.
