### ISSUE TITLE
Forwarding a image doesn't work

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1047]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#feedback`.

**Comment by zlshames** [comment]
This happened to me, but seemed to fix itself after I installed an updated build?

**Comment by tneotia** [comment]
I can't replicate this either. Even with unsupported attachments.

**Comment by zlshames** [comment]
Closing. Can't replicate. probably just a bug from an old build
