### ISSUE TITLE
Message Details Popup - Compensate for tapback menu overlaps

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1049]
From @jjoelj `It's supposed to add a bunch of minimum top padding if the reaction detail widget is visible`

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#support`.

**Comment by CSab6482** [comment]
Here is a photo example
![Screenshot_20210710-143421](https://user-images.githubusercontent.com/53708281/125176592-9d9a0380-e1a2-11eb-9c2c-506dd64e0a79.jpg)
