### ISSUE TITLE
Add Tanay and Joel to the Developers credits in the `About & Links` submenu

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1050]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#requests`.

**Comment by CSab6482** [comment]
Would it also be possible to make it so that tapping your names takes users to your GitHub pages?

**Comment by CSab6482** [comment]
Would it also be possible to make it so that tapping your names takes users to your GitHub pages? Or do you guys not think that would be a good thing to add?

**Comment by tneotia** [comment]
I don't mind if @zlshames and @jjoelj don't.

**Comment by zlshames** [comment]
Yep, 100%, go for it. Otherwise, I'll do it whenever I do some dev again

**Comment by tneotia** [comment]
I'll probably get to it while revamping the settings screens, I'll assign it to myself
