### ISSUE TITLE
Add `onContentCommitted` as a param to `CupertinoTextField.borderless`

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1053]
@tneotia do this before Flutter PR!!!

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@tneot01` in `#android-bugs`.

**Comment by zlshames** [comment]
Fixed @tneotia https://github.com/BlueBubblesApp/flutter/tree/zach/image-insertion
That's the branch it's on ^
