### ISSUE TITLE
Make avatars hi-res again

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1057]
Low-res, despite being faster, is uglier and i've changed my mind and want them to be hi-res

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#support`.

**Comment by zlshames** [comment]
Only do low-res if low memory mode is on

**Comment by zlshames** [comment]
Done
