### ISSUE TITLE
When matching address to contact, sanitize/slug both sides

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1058]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#support`.

**Comment by zlshames** [comment]
This should improve matching against international numbers or numbers that seem to be formatted in non standard ways

**Comment by tneotia** [comment]
@zlshames where exactly does this need to be done?

**Comment by zlshames** [comment]
> @zlshames where exactly does this need to be done?

I think it was meant just to make this string more sanitized? Maybe just slugify it? https://github.com/BlueBubblesApp/BlueBubbles-Android-App/blob/11e1480da149fcf5b0eb50d1ae4aae0528a4cc87/lib/managers/contact_manager.dart#L201

Just to make sure that when it's used to compare to the other values, it'll be as sanitized as possible. Also sanitize the phone number Incase it has dashes and stuff
