### ISSUE TITLE
read receipts still not good

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1060]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#android-bugs`.

**Comment by CSab6482** [comment]
![Image](https://media.discordapp.net/attachments/746560644995612752/864321959511982120/Screenshot_20210712-214516.jpg)

**Comment by CSab6482** [comment]
#939
