### ISSUE TITLE
Upside down images only in message view preview

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1061]
everywhere else, it looks fine. For instance, in the share menu it looks normal, and full screen it looks normal

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#android-bugs`.

**Comment by CSab6482** [comment]
![E192B4CE-5ACB-4AF8-8006-E8E0FC5C1CD4](https://user-images.githubusercontent.com/53708281/125386507-6b3b0280-e36a-11eb-8078-118972aebe38.jpeg)

**Comment by zlshames** [comment]
Marking this as medium difficulty. In reality, I don't know what the issue is or what the possible fix it. That's why it's medium, because it needs research too

**Comment by zlshames** [comment]
This is due to `FlutterImageCompress`

**Comment by zlshames** [comment]
Fixed, my develop branch
