### ISSUE TITLE
Improve reset DB workflow

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1069]
Right now, the reset workflow is kinda iffy and doesn't work well. We need a much better workflow for it. For instance, clear DB, then redirect to the message sync setup page to re-do the entire sync

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#feedback`.

**Comment by zlshames** [comment]
A fair amount of the "reset the DB" code is completed (see `flush()` methods in the models), and I believe the socket manager file may have the function that calls all the flush methods. 

We just need to do a little more to ensure the Message table's get cleared out (or even deleted). Then the finishedSetup car needs

**Comment by zlshames** [comment]
Done. my develop branch. I didn't change much, but it seems to work well now
