### ISSUE TITLE
redownload from server doesn't show when text is attached to an image

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1076]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#general`.

**Comment by CSab6482** [comment]
Might be related to #542 and https://github.com/sgtaziz/WebMessage/issues/51#issuecomment-782634724

**Comment by zlshames** [comment]
> Might be related to #542 and [sgtaziz/WebMessage#51 (comment)](https://github.com/sgtaziz/WebMessage/issues/51#issuecomment-782634724)

Nah I don't think it is. I think it might just be a bad conditional. But... Maybe my guess is wrong

**Comment by tneotia** [comment]
Well all we use is widget.hasAttachment AFAIK, so idk why this would be the case

**Comment by tneotia** [comment]
It's working for me... Don't know if this is still an issue.

**Comment by zlshames** [comment]
We can close for now. Can't replicate atm
