### ISSUE TITLE
Better support for responding to heads-up notifications

### ISSUE THREAD

**Issue by jakeump** [BlueBubblesApp/BlueBubbles-Android-App#1084]
When I'm responding to a text from the heads-up notification while not in the bluebubbles app and the person I'm talking to sends another message, it deletes everything I've written. Would like support for additional messages to show up without deleting any text in progress.

**Comment by zlshames** [comment]
> When I'm responding to a text from the heads-up notification while not in the bluebubbles app and the person I'm talking to sends another message, it deletes everything I've written. Would like support for additional messages to show up without deleting any text in progress.

Is this in your notification shade when you are replying via a notification? I'm a bit confused

**Comment by jakeump** [comment]
Issue replicated with second message from same contact. Have yet to test what happens if you are responding to one message and a different person texts.

Look at the textra workflow – it's perfectly optimized

![Uploading Screenshot_20210719-223010_Samsung Internet.jpg…]()

**Comment by zlshames** [comment]
> Issue replicated with second message from same contact. Have yet to test what happens if you are responding to one message and a different person texts.
> 
> Look at the textra workflow – it's perfectly optimized
> 
> ![Screenshot_20210719-223010_Samsung Internet](https://user-images.githubusercontent.com/87464153/126267065-757623c2-21ec-4da7-9bad-7b18e20b0eae.jpg)

I think this might be an Android bug? If it's through the notification shade, we can't control it. All we can control is the content and what happens when you send the reply

**Comment by tneotia** [comment]
Maybe its because we recreate the reply intent when receiving a new notif?

**Comment by zlshames** [comment]
> Maybe its because we recreate the reply intent when receiving a new notif? We should try only setting the reply intent when its the first notif of its kind.

yeah that's probably it. Though, either i've never noticed the issue or I haven’t run into it

**Comment by tneotia** [comment]
Done (couldn't reproduce when I sent a message to myself, started replying to it, and sent another message from my mac)
