### ISSUE TITLE
Calling from BlueBubbles - remember mobile/work/other selection

### ISSUE THREAD

**Issue by jakeump** [BlueBubblesApp/BlueBubbles-Android-App#1085]
![Screenshot_20210715-1057072](https://user-images.githubusercontent.com/87464153/125848782-0bc7e3eb-7ed8-4eb7-8e7a-898dd536e045.png)

Similar to the image, but I think all that's necessary is a checkbox to "remember this selection." If not checked, the app will not remember and will ask again. 

To implement this, there will also need to be a way to 'forget' the selection if you would like to call a number that you didn't set as default.

**Comment by zlshames** [comment]
Ok, I don't think this is _that_ hard. Here is what needs to be done. 

1. Add a column named something like `preferred_phone` to the handle.dart table (add to the SQL create table code & the DB Migration list)
2. Add the new field to the handle model, and add a helper method to set it (or use update() if you want, though I think a method is more verbose)
3. Add the UI elements to the popup when you choose a number
4. Upon calling (before the call is made), call that model method to change preferred phone (no need to sanitize it first)
5. Modify the code when the call button is clicked to check for a preferred number (sanitize both the DB value and the compared value). If one is present and matches one of the options, make the call

**Comment by jakeump** [comment]
> 6. Implement a way to reset the preferred phone. I say tap and hold on the call button first? But that would require the user to know to do that...

That's a good idea. One other thing you could do is add a little option in the contact's settings page (the one with fetch more messages, clear transcript, etc) to select a default phone number. That way if a user doesn't know or doesn't remember the quick command (hold down phone), they can intuitively change it in the settings page.

**Comment by zlshames** [comment]
@jakeump This will be in our next "alpha" build that gets posted to #android-development in our Discord. We also think we fixed the dupe issue. So I will probably release another beta soon as well
