### ISSUE TITLE
[Material theme] wrong spinner

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1089]
The loading more messages text still uses the iOS style spinner in material mode

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@scarlett` in `#android-bugs`.

**Comment by zlshames** [comment]
Marking as medium because of the breadth of code this touches, however, doing the actual fixes should be easy. I would advise making a ui_helper function to return the widget spinner conditionally based on the skin
