### ISSUE TITLE
Image attachment stack renders loading indicator under images at all times, even when image is loaded

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1090]
this will take a toll on cpu and overall efficiency because it's always rendering it, even if it's behind the image

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#requests`.

**Comment by tneotia** [comment]
Actually now that I look at code I don't think this is an issue...

**Comment by zlshames** [comment]
Yeah I think I fixed it. Closing.
