### ISSUE TITLE
hitbox for chat back button still seems off

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1102]
ever since the change, I've been having issues tapping the back button in the chat. I find myself tapping the back button or notification bubble icon 2, 3, and sometimes 4 times

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#support`.

**Comment by zlshames** [comment]
Leaving this open until i get to test it thoroughly

**Comment by tneotia** [comment]
The hitbox is probably excessively big now lol

**Comment by zlshames** [comment]
> The hitbox is probably excessively big now lol

I'll be the judge of that!! 😈

**Comment by zlshames** [comment]
So, it ain't perfect yet. Keeping it open

**Comment by zlshames** [comment]
Fixed
