### ISSUE TITLE
extra line in tiles in the private api settings page

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1105]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#requests`.

**Comment by zlshames** [comment]
![Screenshot_20210718-214104](https://user-images.githubusercontent.com/18445938/126090843-b1d318cf-9bee-487e-a3e3-584e89b8e660.jpg)
