### ISSUE TITLE
Support for the Conversation widget in Android 12

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1111]
The conversation at the top of this screenshot is an AirMessage chat. ![Image](https://cdn.discordapp.com/attachments/746560677333827584/866712100456759316/Screenshot_20210719-120227.png)

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#requests`.

**Comment by zlshames** [comment]
Marking this as Medium. I couldn't find any articles or guides on this. Maybe I'm just dumb.

**Comment by CSab6482** [comment]
https://www.xda-developers.com/android-12-conversation-widget-first-look/
https://9to5google.com/2021/04/21/android-12-conversations-widget-wallpaper-colors/
https://9to5google.com/2021/06/09/android-12-beta-2-conversations/
https://www.xda-developers.com/android-12-conversations-widget-background-change/
https://nerdschalk.com/what-are-conversation-widgets-in-android-12/

**Comment by zlshames** [comment]
@tneotia your changes to notifications don't handle this specifically, right? We may need @Monica to test because she has Android 12

**Comment by tneotia** [comment]
Nah they shouldn't affect widgets at all. When we fix the launcher shortcuts it might fix this? Idk

**Comment by zlshames** [comment]
> Nah they shouldn't affect widgets at all. When we fix the launcher shortcuts it might fix this? Idk

I think launcher shortcuts are separate tbh

**Comment by tneotia** [comment]
Isn't this working now @zlshames ?

**Comment by zlshames** [comment]
> Isn't this working now @zlshames ?

yep i believe so. closing
