### ISSUE TITLE
Reset DB does not clear tables

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1114]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#android-bugs`.

**Comment by zlshames** [comment]
So it does clear the tables. It just didn’t disconnect from the socket or clear that info, so it would stay connected and receive notifications. I have ironed out some of the workflow so they are disconnected from the socket.
