### ISSUE TITLE
When `Show avatars in non-group chats` is toggled on, show avatar next to typing indicators. Also, remove bubbles on bottom left of typing indicator in material theme.

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1119]
![Image](https://cdn.discordapp.com/attachments/746560644995612752/866890116543152128/Screenshot_20210719-221705.jpg)

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#android-bugs`.

**Comment by SoPat712** [comment]
Can whoever is fixing this also remove the bubbles on the typing indicator when using Material theme? Signal just has one big oval typing indicator, and that seems most appropriate.

**Comment by jjoelj** [comment]
> Can whoever is fixing this also remove the bubbles on the typing indicator when using Material theme? Signal just has one big oval typing indicator, and that seems most appropriate.

Could you send an image of what you mean?

**Comment by jjoelj** [comment]
Oh you mean the bubbles on the bottom left. Yeah I'll do that.
