### ISSUE TITLE
Direct share /sharing outside images into the app appears to be broken on the #android-development builds

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1145]
>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#android-bugs`.

**Comment by zlshames** [comment]
I'm going to keep this open until we confirm it's a lot better

**Comment by tneotia** [comment]
Well not really a question of whether its better as it was like *completely* broken on previous builds. It works now.

**Comment by zlshames** [comment]
> Well not really a question of whether its better as it was like _completely_ broken on previous builds. It should work now.

If I'm honest, I didn't notice any issues with sharing when the app was closed. Hence why I figured we'd wait a bit. But if it was broke for you, and now it's fixed. It trust ya

**Comment by tneotia** [comment]
Weird that it wasn't broke for you... anyways all I care is that it's working now so its all good
