### ISSUE TITLE
Sometimes group chat notifications do not show the group chat name

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1146]
In the screenshot below, there are texts from two different people, so it is a group chat. Next to the `BlueBubbles  5:39 PM` text, there should be a group chat name, but it does not show.

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#android-bugs`.

**Comment by CSab6482** [comment]
![Image](https://media.discordapp.net/attachments/746560644995612752/867522078160584724/Screenshot_20210721-174004_One_UI_Home.jpg)

**Comment by zlshames** [comment]
I'm going to keep this open till we can confirm it's fixed

**Comment by CSab6482** [comment]
I am currently using [this build](https://drive.google.com/file/d/1outba1nkZJrmESZbZZGPjkzn5fXh2WXa/view?usp=drivesdk). Both of these texts are in group chats, but only the bottom one shows the group chat name. Additionally, both the E and T contacts have contact photos, but only the T contact has their contact photo showing.
![Screenshot_20210725-142904_Sync Pro](https://user-images.githubusercontent.com/53708281/126909760-84b49cf0-71d7-408f-a41e-f74ff125825d.jpg)

**Comment by tneotia** [comment]
I'm gonna go ahead and say this is fixed - haven't reproduced in my testing on 2 diff devices after the notif changes but we can always reopen

**Comment by CSab6482** [comment]
The group chat name issue has been fixed, but there are two new issues.
1. Individual chat's show the person's name twice on my phone (S10e OneUI 2.5)
2. Sometimes, contact photos aren't loaded in on notifications.
Should these two issues get their own tickets?
