### ISSUE TITLE
bluebubbles android auto integration

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1149]
is it possible to add an bb integration for android auto like telegram/whats app?

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@Deemo` in `#baffoonery`.

**Comment by Rihcus** [comment]
https://news.androidout.com/2020/10/21/whatsapp-in-android-auto-everything-you-can-and-cant-do/

**Comment by romhacks** [comment]
https://developer.android.com/training/cars/messaging

Relevant Android Developers docs

**Comment by tneotia** [comment]
We are limited by Flutter here: https://github.com/flutter/flutter/issues/26801

Seems like playing audio is possible but no gui or notifications? Don't know for sure.

**Comment by romhacks** [comment]
If GUI support isn't possible, maybe it would be possible to offer Google Assistant integration, which would at least allow handsfree communication in a car. Not sure if flutter supports that either though

**Comment by tneotia** [comment]
It actually doesn't seem too difficult: https://fidev.io/ok-google-flutter/
