### ISSUE TITLE
{Request} Add a color input method other than just the picker

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1161]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@monicow` in `#requests`.

**Comment by zlshames** [comment]
What type of input method? We use a plugin right now, so I think we are limited to that plugin for the most part. We can always make our own edits or make another UI to do it. It's just more work

**Comment by tneotia** [comment]
https://pub.dev/packages/flex_color_picker (switch to this)
