### ISSUE TITLE
search box text is initially black in dark mode in chat creator

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1163]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@tneot01` in `#support`.

**Comment by zlshames** [comment]
This is due to a null error afaik. A similar error happened in the past. I think the old issue had to do with contact stuff. This may be different, but the null error causes the rest of the filtered stuff to not load, and for whatever reason the UI is also effected

**Comment by zlshames** [comment]
This may need a closer look via debug mode from the user having the issue. Though, I don't remember who it was
