### ISSUE TITLE
[Feature Request] When a picture is still being sent, don't let any other texts through until the photo finishes sending

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1165]
Sometimes, the caption that I want to add to a photo delivers first even though I sent it after

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#requests`.

**Comment by zlshames** [comment]
Dupe: https://github.com/BlueBubblesApp/BlueBubbles-Android-App/issues/1172
