### ISSUE TITLE
Improve send animation

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1188]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#general`.

**Comment by zlshames** [comment]
I also get this lag. Not sure if it's 100% of the time. But if not, it's like 80% of the time. It's only a stutter for like 1 ms. Not sure why it happens. My guess is either 1, the sendMessage() call is too intensive. Or 2, the UI gets updated (setState) too many times as it's sending and causes lag

**Comment by zlshames** [comment]
Since this is just a `debuggable` issue, we don't need to fix anything. I have renamed the ticket to reflect an `Optimization` to get rid of the error
