### ISSUE TITLE
When a server can't be connected to, try and show a more detailed error

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1189]
we may need to try and ping the IP or domain to get a legit error

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#desktop-bugs`.

**Comment by zlshames** [comment]
I may have fixed this. Would need to test setup errors

**Comment by tneotia** [comment]
Yeah I get a better error in console now:
`[BlueBubblesApp] [Socket] -> Data: SocketException: Failed host lookup: 'fluffy-elephant-12.loca.lt' (OS Error: No address associated with hostname, errno = 7)`
