### ISSUE TITLE
Fix grey screen bug in server settings

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/BlueBubbles-Android-App#1190]
Not sure why this happened/happens. Joel said it happened for him when he couldn't connect to the server. 

The screenshot Joal shared suggests the issue is due to the socket stream/stream builder widget we use. Just because that's where the grey box starts.

**Comment by tneotia** [comment]
I have literally no idea on this as everything checks out in code, there shouldn't be any null exceptions anywhere.

**Comment by jjoelj** [comment]
Steps to reproduce:
1. Put phone in airplane mode
2. Wait in main chat list until 'Could not connect' popup shows up at the top
3. Click the popup
4. See gray screen

It only happens if I go to it through clicking the popup, not through the settings route.
