### ISSUE TITLE
1.3.0 Beta 1 Android Release - Different APK Signature

### ISSUE THREAD

**Issue by nbetcher** [BlueBubblesApp/BlueBubbles-Android-App#1194]
Hello,
I tried upgrading to the newest 1.3.0 Beta release, Beta 1, on my Android phone, but it the installation failed. After looking at the Android logs through ADB logcat, it indicated that the Beta 1 release is signed with a different signature than that of 1.2.0. Is there any possibility to continue signing with production/release signatures?

Thanks!

**Comment by zlshames** [comment]
> Hello,
> I tried upgrading to the newest 1.3.0 Beta release, Beta 1, on my Android phone, but it the installation failed. After looking at the Android logs through ADB logcat, it indicated that the Beta 1 release is signed with a different signature than that of 1.2.0. Is there any possibility to continue signing with production/release signatures?
> 
> Thanks!

I assume you downloaded the beta from GitHub and _not_ Google Play, correct? If so, it may have just been an issue with that build. When we release the next beta, I'll be sure to make sure the sigs are the same. TBH I'm not sure why they were different with this one... was built the same way

**Comment by zlshames** [comment]
I don’t know if this was just an eff up, but this should be fixed. Google Play and Github have different signatures, that is intended
