### ISSUE TITLE
Apply width and height to image placeholder widget

### ISSUE THREAD

**Issue by romhacks** [BlueBubblesApp/BlueBubbles-Android-App#1203]
Made on behalf of Zach the Almighty

**Comment by zlshames** [comment]
Marking as high priority because this will actually be a quick and easy fix for a kinda annoying UX issue where images loading in will seemingly jump because the preview widget (grey box) is set to a specific size and it will jump to the actual size of the image

**Comment by tneotia** [comment]
We don't know the actual size of the image until it is loaded in as far as I know, so don't think this is possible

**Comment by zlshames** [comment]
> We don't know the actual size of the image until it is loaded in as far as I know, so don't think this is possible

We will once we compress the file, so at least when it's done downloading it can show the size. The image takes a sec to load in usually, so you still see the placeholder widget. Check out my compress helper function
