### ISSUE TITLE
Remove (comment out) the theme selector during setup

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1204]
Remember to modify the page count too?

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#requests`.

**Comment by zlshames** [comment]
If you wanna replace the renders with Images, go for it, but as it stands, that page is too laggy for production use

**Comment by tneotia** [comment]
As much as I don't want to do this I can't make it un-laggy so we should prob remove until I figure out a way to make good looking images
