### ISSUE TITLE
[Material] Sent images don't have enough right padding

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1207]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#android-bugs`.

**Comment by tneotia** [comment]
@zlshames can't reproduce this one either

**Comment by zlshames** [comment]
Closing for now. I don't remember who brought it up. But if they do again, we can reopen or recreate the issue
