### ISSUE TITLE
{Request} iPad-like View for Tablets/Laptops

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1210]
https://medium.com/flutter-community/developing-for-multiple-screen-sizes-and-orientations-in-flutter-fragments-in-flutter-a4c51b849434

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@monicow` in `#requests`.

**Comment by zlshames** [comment]
Dupe: https://github.com/BlueBubblesApp/BlueBubbles-Android-App/issues/641
