### ISSUE TITLE
Fix shortcuts on launcher

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1227]
You can't actually open the shortcut in BB

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@tneot01` in `#requests`.

**Comment by CSab6482** [comment]
Dupe of #295?

**Comment by CSab6482** [comment]
Dupe of #295? @tneotia

**Comment by tneotia** [comment]
> Dupe of #295? @tneotia

Yes
