### ISSUE TITLE
Support conversation features for notifications

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/BlueBubbles-Android-App#1235]
_No content_
> Issue created by BlueBubbles Bot in the BlueBubbles commnity on behalf of @zach in #community-contributions.

**Comment by CSab6482** [comment]
![Image](https://cdn.discordapp.com/attachments/781023536168304641/871786275588436008/Screenshot_20210802-120709_Discord-Beta.jpg)

**Comment by zlshames** [comment]
I’m not entirely sure what the difficulty level is, so marking as medium for now

**Comment by tneotia** [comment]
Done
