### ISSUE TITLE
[Feature Request] Do not auto include `https://` when manually typing an ngrok or other URL

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/BlueBubbles-Android-App#1236]
Given the recent ngrok issues, I was wondering if I could circumvent them by manually running a `/Applications/ngrok tcp 1234` command in terminal and then connecting to the URL from there, but because of the auto inserted `https://`, I was unable to connect to my `tcp://` ngrok link. Strangely enough however, AirMessage can connect to these ngrok links without including the `tcp://` heading, so I'm not sure how that happens.
![Image](https://cdn.discordapp.com/attachments/746560644995612752/871866993186324490/Screenshot_20210802-172654.jpg)
> Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#android-bugs`.

**Comment by zlshames** [comment]
This should be easy. I have a getServerUrl method that prefixes http if it doesn't exist. We need to instead only prefix with http if ANY scheme is found at the start. Aka, tcp, udp, etc. Anything with `://`

**Comment by CSab6482** [comment]
Request to reopen this because of Firebase. If I connect to a `tcp://` address, and then I leave the app, Firebase will disconnect me and I will not be able to reconnect to that address. #1230

**Comment by zlshames** [comment]
> Request to reopen this because of Firebase. If I connect to a `tcp://` address, and then I leave the app, Firebase will disconnect me and I will not be able to reconnect to that address. #1230

Firebase disconnects you? How so

**Comment by CSab6482** [comment]
It defaults me to the server address within the BlueBubbles Server app, which is my DDNS address. However, because I cannot currently portforward, Firebase kicks me off of the `tcp://0.ngrok.io` link that works and attempts to connect me to my DDNS that doesn't work. Of course, it could connect me to a link that works if I have it set up that way, but I want to be able to stay on the `tcp://` link. In hindsight, reopening this ticket doesn't make much sense. Instead, I feel like the information in this ticket should just be referenced in the other one.

**Comment by zlshames** [comment]
> It defaults me to the server address within the BlueBubbles Server app, which is my DDNS address. However, because I cannot currently portforward, Firebase kicks me off of the `tcp://0.ngrok.io` link that works and attempts to connect me to my DDNS that doesn't work. Of course, it could connect me to a link that works if I have it set up that way, but I want to be able to stay on the `tcp://` link. In hindsight, reopening this ticket doesn't make much sense. Instead, I feel like the information in this ticket should just be referenced in the other one.

Sounds like I need to add a server toggle for those extra ngrok opts. Mind opening that ticket?

**Comment by CSab6482** [comment]
Honestly I could also set my DDNS to be the `tcp://0.ngrok.io` link. That should work though it's not ideal.
