### ISSUE TITLE
Add 3rd very small avatar to the groups that have 3 or more members

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/BlueBubbles-Android-App#1258]
This is to be more like iOS 14 group icons. I'm thinking we add it to the top left

**Comment by zlshames** [comment]
@jjoelj assigned this to you since it seems you already started it. If you don’t wanna do it, just unassign yourself

**Comment by tneotia** [comment]
This is done now, right?

**Comment by zlshames** [comment]
Yeoopop
