### ISSUE TITLE
[Redacted Mode] When hide contact icon is disabled, icons are blue

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/BlueBubbles-Android-App#1259]
![Screenshot_20210803-205304](https://user-images.githubusercontent.com/18445938/128104736-6c56dc6d-42d4-4a33-aa3e-d35afefc8a76.jpg)

**Comment by tneotia** [comment]
What are your redacted mode settings? I can't reproduce

![Screenshot_20210803-095335.png](https://user-images.githubusercontent.com/50850142/128105108-7df4e5d1-1fbe-42b9-9390-e89a1eb8d11a.png)

**Comment by zlshames** [comment]
![Screenshot_20210803-210708](https://user-images.githubusercontent.com/18445938/128105719-42c7491f-3092-48c1-8688-4b3822346585.jpg)
