### ISSUE TITLE
When a message fails to send, re-update the last text message with the latest confirmed text

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1262]
https://cdn.discordapp.com/attachments/746560644995612752/872306728413298718/Screen_Recording_20210803-223357.mp4

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#android-bugs`.

**Comment by CSab6482** [comment]
Oh well that was no good, let me try that again

https://user-images.githubusercontent.com/53708281/128113091-6cca2c6d-0a57-40db-8f63-49ab0e6b0213.mp4
