### ISSUE TITLE
[Alpha] Sometimes images don't show

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1272]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#community-contributions`.

**Comment by zlshames** [comment]
Very hard to reproduce. But it happens

**Comment by tneotia** [comment]
Haven't been able to reproduce with latest changes - if people report it we may need to reopen.

**Comment by zlshames** [comment]
Not fixed

**Comment by tneotia** [comment]
Fixed to the best of our ability I would say... Maybe later we can have an additional failsafe.
