### ISSUE TITLE
[Alpha] Notification shade contains a BlueBubbles notification header, but no notifications

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1274]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#community-contributions`.

**Comment by zlshames** [comment]
![Screenshot_20210804-225945](https://user-images.githubusercontent.com/18445938/128284113-4fa8db8c-3396-4cfc-8fad-49af0d5b1cd3.jpg)

**Comment by tneotia** [comment]
We will need to remove the notification with id -1 if we are removing the last notification showing

**Comment by zlshames** [comment]
When we remove a notification, check the count of the notifications. If 0, remove the notification Id -1. The code to count the messages can be taken from New message notification handler. Shouldn't be too bad

**Comment by zlshames** [comment]
Re-opening because this is still bugged. Should be the last thing we need before v1.3.0
