### ISSUE TITLE
[Android 7] Replying via a notification crashes the app

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/BlueBubbles-Android-App#1281]

**Comment by tneotia** [comment]
Stacktrace for this would be helpful

**Comment by zlshames** [comment]
> Stacktrace for this would be helpful

Might be hard to get, however, I assume this is more of just an API issue with replies on older Android devices. Either it needs to be disabled for those devices, or we need to check if the version is older, and if so, use more compatible code

**Comment by tneotia** [comment]
Yup its an API issue with how we do replies. I will disable replies for Android O and under.

**Comment by zlshames** [comment]
> Yup its an API issue with how we do replies. I will disable replies for Android O and under.

Is android O the first version it was introduced in?

**Comment by tneotia** [comment]
Well actually I think it has to do with android auto support - I had to add a flag `SEMANTIC_ACTION_REPLY` which is only supported in API Level 28+ which is probably why it crashes. I am taking a programmatic approach here so we still support them.

**Comment by zlshames** [comment]
> Well actually I think it has to do with android auto support - I had to add a flag `SEMANTIC_ACTION_REPLY` which is only supported in API Level 28+ which is probably why it crashes. I am taking a programmatic approach here so we still support them.

ok cool, yeah just set that flag conditionally based on the version. Make sure to verify the min versions with Android Dev docs

**Comment by tneotia** [comment]
Yessir its done and the notification PR is pushed
