### ISSUE TITLE
Revamp Attachment Downloader

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/BlueBubbles-Android-App#1283]
We need to re-write the Attachment Downloader and convert it into 2 or 3 different classes:

* Attachment Download Manager
  - This will manage all the download queuing
  - This will allow us to set a max downloads at a time variable
* Attachment Downloader State
  - This will manage the download state of the passed Attachment object
  - This will also be where we actually download the attachment and save it and what not

Not sure what a 3rd class can do, maybe just adding more modularization to it.

**Comment by tneotia** [comment]
Is this done or we have more work to do here?
