### ISSUE TITLE
When sending text with a link, the keyboard jitters

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1317]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#android-development`.

**Comment by tneotia** [comment]
Dupe

**Comment by zlshames** [comment]
> Dupe

I don't think it's a dupe. I think it was broke. We fixed it, and now it's broke again

**Comment by tneotia** [comment]
You made an issue for it 17 hours ago so did you fix it very recently?
