### ISSUE TITLE
Sending a message consisting of solely 2 identical links sends the link only once.

### ISSUE THREAD

**Issue by jjoelj** [BlueBubblesApp/BlueBubbles-Android-App#1354]
https://user-images.githubusercontent.com/35714943/129459097-8856dafd-1b07-4007-937e-7eddbd3233ec.mp4

(It's case sensitive)

**Comment by tneotia** [comment]
Maybe this is fixed with the new link change PR?

**Comment by tneotia** [comment]
Yes it is.
