### ISSUE TITLE
Look into why enabling low memory mode prevents group chat notifications from coming in

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/BlueBubbles-Android-App#1374]

**Comment by tneotia** [comment]
I have no idea - I looked into this and see no reason why it shouldn't be working.

**Comment by zlshames** [comment]
> I have no idea - I looked into this and see no reason why it shouldn't be working.

Did you try to replicate it?

**Comment by tneotia** [comment]
Nope  but I've enabled it now if you wanna send notifications

**Comment by tneotia** [comment]
Can we close this? This one seems like a stretch tbh
