### ISSUE TITLE
Make incremental sync fetch messages in batches

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/BlueBubbles-Android-App#1419]
Right now it fetches the last 1k all at once and then ingests them in batches. We should fetch the messages in batches so the initial requests take a shorter time to bring in the newest messages

**Comment by tneotia** [comment]
Is there a way to tell the server to paginate it? Or can we somehow set an offset param so we can paginate ourselves client side?

**Comment by zlshames** [comment]
> Is there a way to tell the server to paginate it? Or can we somehow set an offset param so we can paginate ourselves client side?

Yeah you can set `limit` and `offset`

**Comment by tneotia** [comment]
Yeap done
