### ISSUE TITLE
[1.4.1] Link previews for links in the middle of a text do not show the domain at the bottom

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/BlueBubbles-Android-App#1431]
![Image](https://cdn.discordapp.com/attachments/746692766167334963/882018349599567962/Screenshot_20210830-174507.jpg) ![Image](https://cdn.discordapp.com/attachments/746692766167334963/882018351864492053/Screenshot_20210830-174524.jpg)

**Comment by tneotia** [comment]
Done

**Comment by CSab6482** [comment]
That was so fast
