### ISSUE TITLE
[1.5.0 Alpha] Put start/stop logging within its own 'Troubleshoot' page

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1439]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#android-development`.

**Comment by zlshames** [comment]
This will make it harder to accidentally activate. Maybe we even want to have a prompt telling the user what it means to start logging and confirm they want to do that
