### ISSUE TITLE
Reduce lag when ChatBloc is loading in each chat page

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1443]
if I leave the app and reenter on the chat list, scrolling is very laggy

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#android-development`.

**Comment by zlshames** [comment]
The lag is because we fetch the chats from the DB and add them to the chat bloc. Something we do causes a ton of lag when each page is finished loading and the chat list state updates. Tons of hitters for me and an overall bad UX

**Comment by zlshames** [comment]
We probably need to make it so we don't fully reload the chat bloc each time the app is resumed

**Comment by zlshames** [comment]
I’m also increasing the chat bloc batch size to 15. This way, the first page will also have more items than what your phone can probably display. Might show a short lag for tablets, but it's better than before
