### ISSUE TITLE
make showing link preview hyperlink toggleable

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1444]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#android-bugs`.

**Comment by tneotia** [comment]
I'd say rather than toggleable, just delete the message bubble if the message only consists of a link, because then the message bubble *and* the link preview is kinda pointless.
