### ISSUE TITLE
Decrease container size for files that have no preview, and no need for space

### ISSUE THREAD

**Issue by SoPat712** [BlueBubblesApp/BlueBubbles-Android-App#1460]
![Screenshot_20210902-001151.jpg](https://user-images.githubusercontent.com/30350506/131780632-95ce1fc5-09d7-4a78-9776-cf770c1f884c.jpg)

**Comment by zlshames** [comment]
We could make it flexible so the text has a standard 'x' amount of padding, but the true size is determined by the content. Then each regular file opener widget would be different sizes depending on the text. We probably need to set a max and min size too though
