### ISSUE TITLE
add camera floating action button like signal and select chat to send to

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1464]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@Intellijence` in `#android-bugs`.

**Comment by zlshames** [comment]
This should actually be fairly easy to do...

1. Create the Floating Action Button
    * The hardest part for this would be figuring out where to put it. Should it be behind a toggle? Should the current Floating Action button be more like a menu that when tapped will show 2 options? new chat or camera?
2. When the camera is tapped, open the camera
3. When a picture is taken, it should pop the camera, and the result path to the picture should be returned
4. Pass that File to the ConversationView picked attachments, as well as the isCreator flag
