### ISSUE TITLE
Warning:support for creating chat is limited on MacOs 11 (Big Sur) 

### ISSUE THREAD

**Issue by BxAxNxKxSxY** [BlueBubblesApp/BlueBubbles-Android-App#1520]
Hi guys, 
Im running MacOs 11 (big Sur ) on a virtual machine.Installed everything correctly and at the end when i launched the app and tried to create a message on android phone got the following warning:
"Warning:support for creating chat is limited on MacOs 11 (Big Sur) and are up due to limitations imposed by apple".

any patches for this on the server side?

**Comment by tneotia** [comment]
No this is just a limitation from Apple, we can't do anything about it, sorry :(
