### ISSUE TITLE
Fix Shortcuts / Share Targets on homescreen long press

### ISSUE THREAD

**Issue by Bricktheworld** [BlueBubblesApp/BlueBubbles-Android-App#295]

**Comment by CSab6482** [comment]
Is [this](https://youtu.be/Y7VeFbhmuKg?t=332) the feature that this ticket is about?

**Comment by zlshames** [comment]
Yeah I think. Right now we have the icons, but they then prompt to open with an app, but BB isn't an option. I gotta register the intent for that i think
