### ISSUE TITLE
Unknown group event

### ISSUE THREAD

**Issue by Bricktheworld** [BlueBubblesApp/BlueBubbles-Android-App#353]

**Comment by zlshames** [comment]
This is a screenshot of the outcome: 
![image](https://user-images.githubusercontent.com/18445938/97722224-c78e1880-1aa0-11eb-9d6e-e4589e138ab1.png)

This is a screenshot of the expected outcome: 
![image](https://user-images.githubusercontent.com/18445938/97722246-d07eea00-1aa0-11eb-9cab-ba9e423b4c5e.png)

Not sure what is causing it, but hopefully this should be easy to reproduce

**Comment by zlshames** [comment]
The bug just might be with messages with a space (empty, but not technically). We should probably show those bubbles

**Comment by zlshames** [comment]
I believe I fixed this issue on my branch. Closing
