### ISSUE TITLE
Group contact icons

### ISSUE THREAD

**Issue by Bricktheworld** [BlueBubblesApp/BlueBubbles-Android-App#378]

**Comment by zlshames** [comment]
Not sure if this is possible. Might be on Big Sur, but definitely not on High Sierra or anything semi-old

**Comment by Bricktheworld** [comment]
Nah I just meant like the one that looks like imessage with the contacts stacked. I'm gonna give it a shot

**Comment by Bricktheworld** [comment]
Done
