### ISSUE TITLE
Ability to delete messages (client side only)

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/BlueBubbles-Android-App#401]

**Comment by Bricktheworld** [comment]
Done

**Comment by zlshames** [comment]
I just tested it. It works, but isn't permanent locally. Reopening the ticket.

**Comment by zlshames** [comment]
Actually, this seems like an edge case for me specifically because it's a chat that has only one message in it, from me, and it errored out. It gets deleted, but if you leave and reenter the chat it loads back. I'll fix it. Assigning to me

**Comment by zlshames** [comment]
My branch
