### ISSUE TITLE
Archived chats appearing in main chat list after incremental sync

### ISSUE THREAD

**Issue by Bricktheworld** [BlueBubblesApp/BlueBubbles-Android-App#412]

**Comment by zlshames** [comment]
I believe this is due to the `update()` function updating the `isArchived` property. We can do one of the following:

- Make a new DB column to house our `localArchived` property
- Change `update()` so that it doesn't update the `isArchived` property

**Comment by Bricktheworld** [comment]
Now there is physically no way for this to occur cause I just automatically hide all convo tiles when they are archived and you are in the main chat list and vice versa
