### ISSUE TITLE
Problems with subject lines

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/BlueBubbles-Android-App#415]
![Subject Line Android](https://user-images.githubusercontent.com/53708281/98577111-7a245f00-2289-11eb-9fd9-a8c1751f6b8b.jpg)
![Subject Line iOS](https://user-images.githubusercontent.com/53708281/98577112-7abcf580-2289-11eb-9d9a-36c9558c2061.jpg)
iMessage subject lines don't display properly in the Android client

**Comment by zlshames** [comment]
Good find. I will work on getting this working for you

**Comment by zlshames** [comment]
I've fixed the issue. Code is in my branch. Will be added to the next nightly release (or official release)
