### ISSUE TITLE
Redacted Mode

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/BlueBubbles-Android-App#418]
If a user ever needs to take a screenshot of their app, it would be nice to have a mode that "redacts" all the sensitive information. Last names (or just the whole name), phone numbers, etc.

**Comment by CSab6482** [comment]
This would be cool, I've become very good friends with MSPaint while reporting bugs

**Comment by CSab6482** [comment]
https://github.com/BlueBubblesApp/BlueBubbles-Android-App/issues/729#issuecomment-799740523
I like this take on redacted mode

**Comment by CSab6482** [comment]
Below is some progress that was made by jojejo#3063

Below is redacted mode turned on with the default values.
![Screenshot_1620280374](https://user-images.githubusercontent.com/53708281/117862011-21e21000-b260-11eb-9e56-4e33b74cb8e1.png)
And below this is how the conversation preview page looks like with all of the options toggled on.
![Screenshot_1620279593](https://user-images.githubusercontent.com/53708281/117862078-3c1bee00-b260-11eb-8df7-51f49b608fe2.png)
And below are some general screenshots that jojejo sent.
![Screenshot_1620282280](https://user-images.githubusercontent.com/53708281/117862349-9026d280-b260-11eb-8eb9-69ca7999ab30.png)
![Screenshot_1620282422](https://user-images.githubusercontent.com/53708281/117862362-9321c300-b260-11eb-84a0-b7696228bc90.png)
![Screenshot_1620282463](https://user-images.githubusercontent.com/53708281/117862374-95841d00-b260-11eb-9d11-cb8bdbea2bef.png)
![Screenshot_1620282484](https://user-images.githubusercontent.com/53708281/117862383-97e67700-b260-11eb-936c-3326f53b3341.png)
![Screenshot_1620283298](https://user-images.githubusercontent.com/53708281/117862389-9917a400-b260-11eb-9e63-05004b8b98ef.png)
and some comments from jojejo
> rn the generated text kinda just changes every time the messages are rerendered but I figured since this is going to be rarely used anyway, the slight performance hit isn't too big a problem. The generated contact name changes whenever the app is opened after being taken out of memory
> Those are mainly just cuz I didn't want to be persisting any of this data for no reason

**Comment by zlshames** [comment]
Done, thanks
