### ISSUE TITLE
Contact avatars aren't showing up (nightly)

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/BlueBubbles-Android-App#434]

**Comment by zlshames** [comment]
Is this fixed?

**Comment by zlshames** [comment]
I haven't had this issue in a while. I think I'm going to close it until further notice.

**Comment by zlshames** [comment]
Ran into this issue again. Re-opening. Happened when opening from fully closed via a notification

**Comment by Bricktheworld** [comment]
Yeah I'm gonna fix this today

**Comment by zlshames** [comment]
I got this.

**Comment by zlshames** [comment]
Fixed. ContactAvatarWidget needed to use `getCachedContact()` instead of `getContact()`
