### ISSUE TITLE
Status bar icons don't contrast the theme mode (dark on dark)

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/BlueBubbles-Android-App#441]

**Comment by Bricktheworld** [comment]
Uhhhh, are you sure? I spent time making sure that they did work?

**Comment by zlshames** [comment]
> Uhhhh, are you sure? I spent time making sure that they did work?

At least for me, my status bar icons are black, and my background is a dark color. So it's hard to see

**Comment by zlshames** [comment]
My branch
