### ISSUE TITLE
Make contacts in details page clickable (open in contacts app, not edit)

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/BlueBubbles-Android-App#471]

**Comment by zlshames** [comment]
We already have this lol

**Comment by zlshames** [comment]
Just realized the request is to open the contact card, not the edit menu

**Comment by zlshames** [comment]
I’m dumb

**Comment by zlshames** [comment]
Re-opening because now the request is actually to make it open the contact card.

**Comment by Bricktheworld** [comment]
Close open close open close open

**Comment by Bricktheworld** [comment]
Close open close open close open

**Comment by zlshames** [comment]
My branch
