### ISSUE TITLE
Downloading attachments to device doesn't seem to work

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/BlueBubbles-Android-App#472]

**Comment by SoPat712** [comment]
You can close this, I said that it started working afterwards. This is @intellijence on discord btw.

**Comment by zlshames** [comment]
> You can close this, I said that it started working afterwards. This is @intellijence on discord btw.

While this is similar to your issue, I still think there is room for improvement on our end

**Comment by SoPat712** [comment]
Yeah ig. Wait I don't remember making this discord account, whose account am I on?

**Comment by Bricktheworld** [comment]
lmao

**Comment by zlshames** [comment]
Fixed, my branch. Issue was legacy external storage was set to false
