### ISSUE TITLE
Setting accent color to something dumb themes the theme menu and makes it hard to fix

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/BlueBubbles-Android-App#478]
"If I set accent color to all white I can't find the button to fix it lol"

**Comment by zlshames** [comment]
Should we even worry about this? Seems like the users just need to stop doing that, lmao

**Comment by Bricktheworld** [comment]
No I'll do it

**Comment by Bricktheworld** [comment]
Fixed
