### ISSUE TITLE
Error (22): C39C is displayed when starting a new chat using a manually enterted number that doesn't particiapte in iMessage (Android)

### ISSUE THREAD

**Issue by onlyonekenobi** [BlueBubblesApp/BlueBubbles-Android-App#486]
I went to create a new chat.
I wasn't sure if the person I wanted to text had an iPhone or not so I manually entered their number, typed a message and hit send.
I immediatly got the error dialog, Error (22): C39C, with the Retry, Cancel, Delete options.

Turns out this person had an Android so I used my native messaging app.

Expected behavior would be some feedback saying the person I am texting doesn't have iMessage.

**Comment by Bricktheworld** [comment]
Gotcha, this feels like more of a server fix that we need to implement

**Comment by zlshames** [comment]
![Screenshot_20201127-083914](https://user-images.githubusercontent.com/18445938/100455079-13c27d80-308c-11eb-8612-9fe048b6491f.jpg)

Fantastic

**Comment by zlshames** [comment]
Could handle it better on the server side, yes, but maybe also we want to handle it on client as well. Like if the osascript has this error, map it to a friendly error

**Comment by zlshames** [comment]
Fixed. my branch
