### ISSUE TITLE
Sometimes avatars don't show in new chat creator

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/BlueBubbles-Android-App#494]

**Comment by Bricktheworld** [comment]
This is probably because of cached contact, we need to redo the contact system anyway

**Comment by zlshames** [comment]
> This is probably because of cached contact, we need to redo the contact system anyway

Nah, it's not. What's weird is that sometimes a contact has multiple addresses. And 2 of those will have the correct avatar, but the 3rd (same contact) will be just the letters. Might be a key issue again

**Comment by zlshames** [comment]
Fixed. This was because certain addresses don't have handles associated with them. Thus, they aren't in the cached contact handles. I had to make a check that if it wasn't in the cache, do a lookup in the actual contacts service.
