### ISSUE TITLE
Fix share menu conversations

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/BlueBubbles-Android-App#499]
Brandon, you keep not including recent conversations at the top of the share menu. Quit it. They MUST be at the top.

**Comment by Bricktheworld** [comment]
They are there now... just when the user types nothing

**Comment by Bricktheworld** [comment]
This is legit not a bug, the way you were doing it before made it so that there were dupe contacts... why would we do it like that, it's just confusing
