### ISSUE TITLE
Fix issues with opening contact from details page

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/BlueBubbles-Android-App#503]

**Comment by CSab6482** [comment]
Does this also apply for creating a new contact from the details page?

**Comment by zlshames** [comment]
> Does this also apply for creating a new contact from the details page?

I think so. This issue was just that on some phones, tapping a contact would show the contact card. On others, it would create a new one/show the edit screen (which isn't what we want). We want the contact card at all times

**Comment by zlshames** [comment]
I think I fixed this... hopefully i did. Closing for now.
