### ISSUE TITLE
Tutorial on the android app, instead of on the website.

### ISSUE THREAD

**Issue by SoPat712** [BlueBubblesApp/BlueBubbles-Android-App#516]
It can guide them to a short download link, and steps would be on the phone, meaning they don't have to switch back and forth between browser links, setting up FCM.

**Comment by zlshames** [comment]
Not sure I understand the request. Can you please explain a bit further @SoPat712 ?

**Comment by SoPat712** [comment]
Actually forget about it, this is kinda stupid.
