### ISSUE TITLE
Scroll lag

### ISSUE THREAD

**Issue by SoPat712** [BlueBubblesApp/BlueBubbles-Android-App#517]
Fragment(idk what it is in flutter, container?) starts lagging when scrolling up too far in the message history.

To reproduce, scroll up a little bit, and then hit the scroll to bottom button. You'll see it's still smooth. Scroll up 100 or so messages, and it massively stutters when you hit scroll to bottom.

**Comment by zlshames** [comment]
Any idea if you have a lot of hyperlinks? Or is it just normal messages?

**Comment by SoPat712** [comment]
It's mostly normal messages.
