### ISSUE TITLE
Animation when opening keyboard

### ISSUE THREAD

**Issue by Bricktheworld** [BlueBubblesApp/BlueBubbles-Android-App#518]

**Comment by zlshames** [comment]
Looking at our bluebubbles text field widget, don't we already wrap it in AnimatedSize? Changing the duration doesn't do anything, neither does changing it to an AnimatedContainer. For reference, I was looking at this: https://medium.com/flutter-community/animate-your-ui-when-keyboard-appears-in-flutter-86465a2a70a4

**Comment by zlshames** [comment]
This link might also be useful: https://github.com/flutter/flutter/issues/19279#issuecomment-560331729

**Comment by Bricktheworld** [comment]
There is a bit more to do other than changing the animatedcontainer, it's a much more low level issue that I will solve using a package

**Comment by Bricktheworld** [comment]
Done
