### ISSUE TITLE
Cannot send VCF File

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/BlueBubbles-Android-App#530]
Crash when sending VCF: https://user-images.githubusercontent.com/53708281/101115394-49e28e80-35b1-11eb-956e-2e1d24e9a16a.gif

This might just be related to issues with the share menu?

**Comment by Bricktheworld** [comment]
I should have already fixed the share menu bug, please pull my branch and or use the latest beta branch

**Comment by zlshames** [comment]
This is fixed
