### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by Bricktheworld** [BlueBubblesApp/BlueBubbles-Android-App#533]
Ok this is getting ridiculous, why does showing the scroll down button lag the frames, why does loading older messages lag everything...

**Comment by zlshames** [comment]
i think we're going to need to evaluate all the re-build scenarios. And figure out which widgets are rebuilding the most, and which can we avoid

**Comment by Bricktheworld** [comment]
Messages view is one that I'd love to avoid, but I'll probably have to modify the flutter framework to get some more performance. Been trying to fix that for ages but flutter has shitty bug in it

**Comment by zlshames** [comment]
> Messages view is one that I'd love to avoid, but I'll probably have to modify the flutter framework to get some more performance. Been trying to fix that for ages but flutter has shitty bug in it

And you're sure it's not fixed in later versions?

**Comment by Bricktheworld** [comment]
It is not, it's a root level issue with flutter. It's not really a bug persay, but it's just how it works. It's okay though because I've found a better solution which will fix a lot of issues

**Comment by Bricktheworld** [comment]
I think I've mostly fixed the performance issues, if there are more I'll fix them as I go but rn the app feels super snappy
