### ISSUE TITLE
Customize swipe menu

### ISSUE THREAD

**Issue by Bricktheworld** [BlueBubblesApp/BlueBubbles-Android-App#536]
So that users have options: such as delete, archive, mark unread, silence, pin etc

**Comment by SoPat712** [comment]
I can add a customization in settings, not sure how it is supposed to look, though. Should it just give the user the ability to reorder the swipe menu?

**Comment by zlshames** [comment]
> I can add a customization in settings, not sure how it is supposed to look, though. Should it just give the user the ability to reorder the swipe menu?

I think the idea was that the user could enable/disabled each of the slide menus. Also, if you do this, please do this off of the beta branch and we can merge the changes into the nightly. Imo, most of your work should be off my beta branch, unless it has to do with the private api

**Comment by SoPat712** [comment]
Alright, I can do that. It's just that previously, your beta branch didn't have the material theme changes, and I'm just gonna wait for that stuff to be merged into beta before switching branches, because I literally only use Material.

**Comment by SoPat712** [comment]
And I'll also look into the enabling/disabling thing. Not sure why someone would want to disable parts of it though, they just lose functionality. ¯\_(ツ)_/¯ I'll make the change when I have time.

**Comment by zlshames** [comment]
Marking this as hard because they would need to create a UI around it for editing it

**Comment by SoPat712** [comment]
I have no idea how to make this look good. I have functionality, but it still just looks like garbage.

**Comment by zlshames** [comment]
@tneotia maybe you can look at how to spruce this up a bit. You seem to be way better at UI than I am

**Comment by tneotia** [comment]
> I have no idea how to make this look good. I have functionality, but it still just looks like garbage.

Hey, functionality is a huge part of making a feature! That's where all software starts out - then we make it look pretty. Nice work so far :)

> @tneotia maybe you can look at how to spruce this up a bit.

I can attack this today if you want. I was also gonna try and add the theme selector to the setup screen.

**Comment by zlshames** [comment]
> > I have no idea how to make this look good. I have functionality, but it still just looks like garbage.
> 
> Hey, functionality is a huge part of making a feature! That's where all software starts out - then we make it look pretty. Nice work so far :)
> 
> > @tneotia maybe you can look at how to spruce this up a bit.
> 
> I can attack this today if you want. I was also gonna try and add the theme selector to the setup screen.

i don’t think there is any rush to do this. I would work on what you want to work on. No deadlines, no priorities board really... up to you. Though, I don’t think there's _that_ many people asking for the feature as of now

**Comment by tneotia** [comment]
Nah lol its not like I don't want to work on this. There are certain things I don't have the *know-how* to figure out, so I leave those alone, but whatever I think I can do, I do it. My priority list is pretty simple: 1) Whatever is `priority: high` that I can do 2) Literally anything else I can do. So I'll do this, the dupe messages, the theme selector, and the image placeholder over the next few days.

**Comment by zlshames** [comment]
> Nah lol its not like I don't want to work on this. There are certain things I don't have the _know-how_ to figure out, so I leave those alone, but whatever I think I can do, I do it. My priority list is pretty simple: 1) Whatever is `priority: high` that I can do 2) Literally anything else I can do. So I'll do this, the dupe messages, the theme selector, and the image placeholder over the next few days.

heh, it's more for my own good. I hate _asking_ people to do things, especially for an open-source project with little to no stakes and no compensation other than gratification, haha

**Comment by tneotia** [comment]
I know lol I get my compensation from my other app. I enjoy devving in my free time :)

I live for those heart and fire emojis in discord lolol (jk)
