### ISSUE TITLE
GIFs sent on Android get heavily compressed

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/BlueBubbles-Android-App#545]
I haven't tested this on desktop, but here we can see me sending the same GIF twice, once through BlueBubbles on Android and the other through SMServer from the Brave browser on the same phone. It looks fine in BlueBubbles but everywhere else it's compressed.
![Android GIF](https://user-images.githubusercontent.com/53708281/101957326-3ba6fa80-3bcf-11eb-8d16-46befb2724aa.jpg)
![iOS GIF](https://user-images.githubusercontent.com/53708281/101957325-3b0e6400-3bcf-11eb-9f38-a255f8cae6de.png)

**Comment by zlshames** [comment]
I'm wondering if this is an issue because of the actual gif keyboard, not the server. For instance the gif keyboard just gives us the link to download the gif. We take that and send the data to the server. We don't compress it iirc. Is that right @Bricktheworld ?

**Comment by Bricktheworld** [comment]
Yeah it is, we don't compress

**Comment by zlshames** [comment]
After some research, the service Google uses is called tenor: https://tenor.com/
Looking at their site, they offer SD and HD versions of GIFs. I wonder if Google purposely chooses the SD one. And from the looks of it, it does.

You're also able to specify the size in your API query: 
![image](https://user-images.githubusercontent.com/18445938/102655079-b2984200-413f-11eb-97aa-53ab1a26416d.png)

My guess is Google just requests the smallest size

**Comment by zlshames** [comment]
Sorry, but I think I need to close this just because it might not be possible, unless we find a way to fetch the bigger version by modifying the URL

**Comment by CSab6482** [comment]
![PNG Image (1)](https://user-images.githubusercontent.com/53708281/116325859-2bb04180-a791-11eb-9bf9-f25e37467576.png)
![Screenshot_20210427-194140](https://user-images.githubusercontent.com/53708281/116325860-2c48d800-a791-11eb-8bf9-21cf1a3fc029.jpg)

**Comment by CSab6482** [comment]
![cvq2pral2rv61](https://user-images.githubusercontent.com/53708281/118325355-5a3c5500-b4d1-11eb-9b9c-ce96ec395542.gif)

**Comment by CSab6482** [comment]
![image](https://user-images.githubusercontent.com/53708281/119216088-80e52780-ba9f-11eb-94ed-ed7948b69dda.png)
