### ISSUE TITLE
When compressing images, compress on a sliding scale based on size

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/BlueBubbles-Android-App#557]

**Comment by Bricktheworld** [comment]
What the fuck does this mean

**Comment by zlshames** [comment]
> What the fuck does this mean

For instance, if I have a super small image that's only 100kb, we don't want to compress it to 25% because that would be 25kb and so much detail is lost. I think that it should be compressed less and less as the size of the image goes down

**Comment by zlshames** [comment]
Don't need this anymore
