### ISSUE TITLE
Support for .pages attachments

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/BlueBubbles-Android-App#561]
Currently, they show up as nothing in the message view. However, in the notification text, they show up as "1 link"

**Comment by tneotia** [comment]
This is not super easy because .pages attachments come in with no mime type. It'll take a lot of bug checking to make sure we don't screw up while implementing this, and simply creating a checker for .pages is not a great idea. It should be more all-encompassing.

**Comment by zlshames** [comment]
If the mimetype is null, I believe you can check the balloonTypeId or something (I forget the name). That might have an ID in it like com.apple.pages

**Comment by tneotia** [comment]
This works now
