### ISSUE TITLE
Australian phone numbers completely wrong

### ISSUE THREAD

**Issue by Bricktheworld** [BlueBubblesApp/BlueBubbles-Android-App#572]
"hey, so i just got it working on my phone, but one issue im having is that the 2/3 contacts i tested this out with dont have their names on the message list, just 4 random numbers before their number begins. so for example, in australia, our numbers are 0401 111 111, but on the app it shows +1 (142) 111-1111, any idea whats going on?"

**Comment by zlshames** [comment]
I'll do this

**Comment by zlshames** [comment]
My branch. Basically, I had to replace the `formatPhoneNumber()` function. I replaced the code in it with the FlutterLibphonenumber code so that we can parse the phone number based on the user's current region. It will then display the phone number according to that region. My beta branch
