### ISSUE TITLE
[Nightly] Chat histories sometimes don't show up when sending media

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/BlueBubbles-Android-App#573]
When a photo or other file is shared and you tap on a chat with previous messages, sometimes a black screen just comes up and the chat history isn't shown. The message can always go through however.

**Comment by zlshames** [comment]
I think I've gotten this as well. Noticed it when testing that disappearing attachment bug

**Comment by zlshames** [comment]
Fixed. My beta branch
