### ISSUE TITLE
Add the ability to open the tapback menu with a double tap

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/BlueBubbles-Android-App#574]
I feel so pretentious writing these demanding titles so I'd just like to point out I only do it for formality's sake, thanks for everything Brandon and Merry early Christmas

**Comment by zlshames** [comment]
lol we do it ourselves. It's more of a ledger of things to do, they dont  need to be formal unless it's complicated. I'll work on this

**Comment by zlshames** [comment]
Done. It will be done via an option in `User Experience Settings`. My branch
