### ISSUE TITLE
Dividers on the app should only extend until the contact name instead of the contact pic.


### ISSUE THREAD

**Issue by officialcdi** [BlueBubblesApp/BlueBubbles-Android-App#575]
____________
Pic name

**Comment by zlshames** [comment]
This may require us to edit the actual flutter widget for the listTile. Not sure we want to do that, but I'll let @Bricktheworld decide

**Comment by Bricktheworld** [comment]
No this is incredibly easy to fix

**Comment by zlshames** [comment]
I think we fixed this. Closing.
