### ISSUE TITLE
Add edit button and the option to have the create chat button on the top

### ISSUE THREAD

**Issue by officialcdi** [BlueBubblesApp/BlueBubbles-Android-App#577]
This one is just to fix the huge gap at the top.
![image1.png](https://user-images.githubusercontent.com/62184980/103092261-af300b00-45c4-11eb-9cd3-5fd6c8cde0cf.png)

**Comment by officialcdi** [comment]
![Screenshot_20201224-084851.png](https://user-images.githubusercontent.com/62184980/103092339-e7cfe480-45c4-11eb-968d-fb7b7b2afc01.png)

**Comment by zlshames** [comment]
What would the edit button do? Or are you just saying move the "settings/archive" button to the Edit side, then move the floating button to the top?

**Comment by Bricktheworld** [comment]
I don't wanna move the new create chat to the top, but sure we can add an edit button

**Comment by zlshames** [comment]
@officialcdi im sorry, but im going to close this. I don't think we need an edit button. Veto!
