### ISSUE TITLE
Split screen landscape mode

### ISSUE THREAD

**Issue by officialcdi** [BlueBubblesApp/BlueBubbles-Android-App#578]
This one is on plus size iPhones. I don't really think anyone uses it, but it's something to maybe add in the future to make the app closer to 1:1.

![iOS-10-Messages-iPhone-screenshot-004.png](https://user-images.githubusercontent.com/62184980/103092447-3f6e5000-45c5-11eb-9e5e-c1ee5e6c66ea.png)

**Comment by zlshames** [comment]
This would be cool, but unfortunately, probably will be backlogged

**Comment by zlshames** [comment]
Duplicate of: https://github.com/BlueBubblesApp/BlueBubbles-Android-App/issues/578
Closing
