### ISSUE TITLE
[Material Theme] Move notification dot to the right side

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/BlueBubbles-Android-App#580]

**Comment by zlshames** [comment]
@CSab6482 can you provide a screenshot? Otherwise, lmk if I should close it

**Comment by CSab6482** [comment]
> @CSab6482 can you provide a screenshot? Otherwise, lmk if I should close it

![Screenshot_20210616-202401](https://user-images.githubusercontent.com/53708281/122311723-d23ad800-cee0-11eb-96cb-d05c75dd80ab.jpg)
The top chat shows this well because both the notification bubble and the contact avatar are blue

**Comment by CSab6482** [comment]
![Screenshot_20210616-202720_AirMessage](https://user-images.githubusercontent.com/53708281/122312220-c1d72d00-cee1-11eb-9a1c-3a229f2129a2.jpg)
I like how AirMessage does it, especially with the numbered notification

**Comment by CSab6482** [comment]
I like how AirMessage does it, especially with the numbered notification
![Screenshot_20210616-202720_AirMessage](https://user-images.githubusercontent.com/53708281/122312220-c1d72d00-cee1-11eb-9a1c-3a229f2129a2.jpg)

**Comment by CSab6482** [comment]
> > @CSab6482 can you provide a screenshot? Otherwise, lmk if I should close it
> 
> ![Screenshot_20210616-202401](https://user-images.githubusercontent.com/53708281/122311723-d23ad800-cee0-11eb-96cb-d05c75dd80ab.jpg)
> The top chat shows this well because both the notification bubble and the contact avatar are blue

![image](https://user-images.githubusercontent.com/53708281/124399452-9037d180-dce9-11eb-829a-f8695f7f484d.png)
It looks like this has been changed, and I definitely think the change is good enough to close the ticket. However, the title says to move the notification dot, so is that still a goal?

**Comment by tneotia** [comment]
@CSab6482 up to you because you opened it. I think its fine the way it is, I don't see any issues with this not looking like "material" theme.
