### ISSUE TITLE
Video didn't load/download on Nightly

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/BlueBubbles-Android-App#581]
![Screenshot_20201224-171709](https://user-images.githubusercontent.com/53708281/103108082-5edf9a00-4612-11eb-93a7-2b2052ca0332.jpg)
![Screenshot_20201224-171621](https://user-images.githubusercontent.com/53708281/103108083-5f783080-4612-11eb-9672-21864072c14a.jpg)

**Comment by Bricktheworld** [comment]
I believe that the video is just a preview correct? What happens if you try to play it?

**Comment by CSab6482** [comment]
Tapping it did nothing, and exiting the app did not fix it either. I downloaded it and couldn't play it either, my phone gave me a gray screen with a white exclamation point.

**Comment by CSab6482** [comment]
In issue #635 I said I've only had this bug once, but I just got it again and I'd estimate it's happened between 4-6 times total

**Comment by CSab6482** [comment]
![Screenshot_20210223-164244](https://user-images.githubusercontent.com/53708281/108912276-6dd4cf80-75f6-11eb-8be2-84f26e8fbaa6.jpg)
![Screenshot_20210223-164305](https://user-images.githubusercontent.com/53708281/108912295-72998380-75f6-11eb-8a64-f92a5828a6f3.jpg)
I got it again on the 0.1.16 rc-1, but thankfully the Re-download from Server button properly loaded the video. I'm not sure if this ticket should close or not since the workaround exists though. Let me know 👍

**Comment by zlshames** [comment]
@CSab6482 should i close this

**Comment by CSab6482** [comment]
I think this is safe to close because it's probably related to #817, and also the redownload button works fine (though you do have to exit and re-enter the chat for the redownload changes to show)

**Comment by CSab6482** [comment]
dacmbibs#0121 in the Discord faced this issue, and using the re-download from server button did not fix it for them.
[Image](https://media.discordapp.net/attachments/746560644995612752/865246812611936256/Screenshot_20210715-110054.png)
