### ISSUE TITLE
Remove tail when message tails are open

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/BlueBubbles-Android-App#596]
![Screenshot_20201228-223348](https://user-images.githubusercontent.com/53708281/103257093-ca50a100-495d-11eb-9bf8-e418c635dae6.jpg)
![Screenshot_20201228-223356](https://user-images.githubusercontent.com/53708281/103257094-cae93780-495d-11eb-89e3-e2b78fed2f83.jpg)

**Comment by cynical89** [comment]
This is part of the message tail. It's a box with one corner rounded the color of the message bubble with another box with a rounded corner over it the same color as the background. Clever work around for the tail, but it needs some updating for this view.

It's not a super quick fix atm. Might need to create an svg for the tail and display that to get rid of the box.

**Comment by CSab6482** [comment]
That's quite the creative tail solution, thanks for explaining it!
