### ISSUE TITLE
Sharing and sending an image from an external app sometimes keeps the image in the queue

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/BlueBubbles-Android-App#600]
![Screenshot_20201229-115848](https://user-images.githubusercontent.com/53708281/103300656-5f3eb300-49cd-11eb-8c9f-14bb3dcc4010.jpg)
Let me know if more details are needed

**Comment by CSab6482** [comment]
![Screenshot_20201229-121627](https://user-images.githubusercontent.com/53708281/103301588-b6de1e00-49cf-11eb-99aa-28ffa008ff76.jpg)

**Comment by zlshames** [comment]
Fixed. My branch
