### ISSUE TITLE
Web previews don't fully load on nightly

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/BlueBubbles-Android-App#604]
![tempFileForShare_20201230-103316](https://user-images.githubusercontent.com/53708281/103365269-af7d4a00-4a8d-11eb-82d0-f69a52751be3.jpg)
This specific one fixed itself about 20 minutes later

**Comment by CSab6482** [comment]
![20201230_112500](https://user-images.githubusercontent.com/53708281/103366899-b4dc9380-4a91-11eb-9110-e56c62b89ced.jpg)

**Comment by zlshames** [comment]
This is technically a duplicate of this: https://github.com/BlueBubblesApp/BlueBubbles-Android-App/issues/817
