### ISSUE TITLE
Fix dupe sending issue

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/BlueBubbles-Android-App#612]
Idk why but some messages are duping when they send. Not sure if I need to implement something on the server side or on the android side. Maybe I'll just check the queue service?

**Comment by CSab6482** [comment]
#788 #805

**Comment by zlshames** [comment]
This can happen when switching from cellular to wifi right as you send the message

**Comment by CSab6482** [comment]
I think this has been fixed with Server release 1.2.0, so hopefully that's the case :)
