### ISSUE TITLE
Option to use contact names as textfield placeholders

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/BlueBubbles-Android-App#614]

**Comment by CSab6482** [comment]
When I use this feature on a group chat whose name takes up more than two lines and I type a message, it leaves a strange gap

**Comment by zlshames** [comment]
> When I use this feature on a group chat whose name takes up more than two lines and I type a message, it leaves a strange gap

Can you take a screenshot of the issue and upload it here? Also, can you let me know what your "expected" outcome is so I can fix it according to that?

**Comment by CSab6482** [comment]
![Screenshot_20210122-090436_Gallery](https://user-images.githubusercontent.com/53708281/105500596-16f37780-5c91-11eb-8520-19581f83a9f3.jpg)
^ expected
![Screenshot_20210122-090358](https://user-images.githubusercontent.com/53708281/105500613-1fe44900-5c91-11eb-8f59-4537a0443087.jpg)
^ with long group name

**Comment by zlshames** [comment]
Already done. Closing
