### ISSUE TITLE
Strip/ignore the e: before a known contact (in this case myself)

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/BlueBubbles-Android-App#618]
![tempFileForShare_20210103-113819](https://user-images.githubusercontent.com/53708281/103486384-74e81a00-4dcb-11eb-8cce-4ee8d37a297d.jpg)
![tempFileForShare_20210103-113948](https://user-images.githubusercontent.com/53708281/103486385-7580b080-4dcb-11eb-9976-33234d7a546e.jpg)
![20210103_114534](https://user-images.githubusercontent.com/53708281/103486386-76194700-4dcb-11eb-9a84-c4b19ce3079a.jpg)

**Comment by zlshames** [comment]
This should be an easy fix. Basically, in the `contact_manager.dart` file, when we cache/save the contacts map, check emails to see if it startsWith "e:". If so, remove it before it's cached

**Comment by zlshames** [comment]
This _should_ be fixed now in my branch. Closing.
