### ISSUE TITLE
Delivered/Read receipts sometimes don't show up until I exit and re-enter a chat

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/BlueBubbles-Android-App#619]
I scrolled through the open issues and I couldn't find this so I thought I'd open a ticket for it. It's a menial thing and only happens from time to time.

**Comment by zlshames** [comment]
Looking at this now, i think I know the issue. Basically, when I load the delivered receipt, i never reload it again. So sometimes it wont show.

**Comment by zlshames** [comment]
I believe I fixed it. Closing. My beta branch
