### ISSUE TITLE
Add additional controls to video fullscreen viewer

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/BlueBubbles-Android-App#623]

**Comment by tneotia** [comment]
Additional controls like what? Skip/Reverse 10 sec?

**Comment by zlshames** [comment]
Yeah I would say rewind 5 seconds, play/pause, fast forward 5 seconds. I kinda just want to revamp the video player. It's kinda ugly

**Comment by tneotia** [comment]
Factoids
