### ISSUE TITLE
Read and Delivered receipts shouldn't be mutually exclusive

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#632]
An older message may be read, even if the newest isn't read. We need to keep the read receipt on the previous message until the new message is read
---
Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#android-bugs`.

**Comment by zlshames** [comment]
FIxed. My beta branch
