### ISSUE TITLE
[Nightly] Sharing an image to a group chat and lost all contact info on the messages (reappeared after sending)

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/BlueBubbles-Android-App#633]
![20210105_225619](https://user-images.githubusercontent.com/53708281/103727532-7c651a00-4fa9-11eb-9f1a-933f9d27287e.jpg)
![20210105_225727](https://user-images.githubusercontent.com/53708281/103727535-7cfdb080-4fa9-11eb-9a54-3b14e606d8a3.jpg)
Interestingly enough this is the first time I didn't have the bug where the picture stays in my queue after sending it

**Comment by CSab6482** [comment]
I think it is safe to say that this only affects the material theme

**Comment by zlshames** [comment]
@CSab6482 can i close this?
