### ISSUE TITLE
Messages received out of order when sent in quick succession

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/BlueBubbles-Android-App#635]
Much like [this bug here](https://github.com/BlueBubblesApp/BlueBubbles-Android-App/issues/581) I've only had it happen once, but I received these three messages probably within one second of each other and they displayed out of order. Quitting the app from the app switcher and going back in didn't fix it.
![20210106_124301](https://user-images.githubusercontent.com/53708281/103802479-321d8080-501d-11eb-8e75-6fbc34080784.jpg)
![20210106_124421](https://user-images.githubusercontent.com/53708281/103802481-32b61700-501d-11eb-9062-3ecec6aa570d.png)

**Comment by zlshames** [comment]
@CSab6482 should i close this?
