### ISSUE TITLE
Request to either remove the pause button when playing a video from a preview or move it to the bottom left corner

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/BlueBubbles-Android-App#636]
![20210106_132714](https://user-images.githubusercontent.com/53708281/103806444-0d2c0c00-5023-11eb-9710-86278aa24f19.jpg)

**Comment by CSab6482** [comment]
![20210110_004734](https://user-images.githubusercontent.com/53708281/104115443-88204b80-52dd-11eb-910f-402bc452feb2.jpg)
In this instance the pause button didn't go away after the video finished playing

**Comment by zlshames** [comment]
I'm closing this. i dont think this is an issue anymore
