### ISSUE TITLE
Sent messages don't sync properly

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/BlueBubbles-Android-App#643]
This was a conversation I had on iOS, and when I went to check it in BlueBubbles, only the received messages were showing up. Exiting and re-entering the chat fixed the issue, I'll switch to the PlayStore build to see if this bug happens there too.
![Android 1](https://user-images.githubusercontent.com/53708281/103947559-41c4c400-5106-11eb-8cae-fd5e6e751029.jpg)
![Android 2](https://user-images.githubusercontent.com/53708281/103947562-438e8780-5106-11eb-9b3f-b722377a191b.jpg)

**Comment by zlshames** [comment]
@CSab6482 is this still an issue?

**Comment by CSab6482** [comment]
Yes but I’m writing it off as an Apple bug as I get this bug on my native iMessage devices when I have the same conversation open on multiple devices. It’s a weird one.
