### ISSUE TITLE
Fix the following issues with custom avatar bubbles

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/BlueBubbles-Android-App#651]
- Don't make it clickable everywhere
- Make the colorful bubbles reflect the same colors as set via custom
- Custom colors aren't honored in message_view.dart

**Comment by SoPat712** [comment]
They are honored the first time you set them, then after you restart, or close the app once, the app defaults back to the seed color.

**Comment by zlshames** [comment]
Finished.
