### ISSUE TITLE
Send Delay toggle not toggling

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#658]
I turned the toggle off, force close the app (I always do that to every app I finish using), go back in and write a message in a chat and press send (I expect the behavior to be normal, no send delays cause I shut it off) but it defaults to send delay and when I go check the toggle in settings, it's turned back on by itself

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@Cynical` in `#android-bugs`.

**Comment by zlshames** [comment]
This was because the settings don't technically save unless you back out of the page. Maybe I should change that. Closing this ticket as im going to change some other things
