### ISSUE TITLE
duplicate smart reply option in Zach/nightly

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#661]
In User experience settings, there are 2 Smart Replies options. Get rid of the older one, idk which one that is.

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@Intellijence` in `#requests`.

**Comment by SoPat712** [comment]
#675

**Comment by zlshames** [comment]
Done, my branch
