### ISSUE TITLE
Connection Indicator zach/nightly for Material theme

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#662]
Add a connection indicator to the material theme's appBar in conversation_list or something.

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@Intellijence` in `#requests`.

**Comment by SoPat712** [comment]
#675

**Comment by CSab6482** [comment]
Closed?

**Comment by zlshames** [comment]
This was fixed I think. Closing
