### ISSUE TITLE
appBar in ConversationViewMixin Material not using the color associated with the handle, instead utilizes toColorGradient

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#663]
In Material theme, the top appBar is colored by lightening bubbleColor in conversationViewMixin, it should be colored instead by checking if the conversation has a user-changed color first.

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@Intellijence` in `#requests`.

**Comment by SoPat712** [comment]
I just made them all black, the gradient colors looked weird anyway. I'll make it a preference in ux settings.

**Comment by SoPat712** [comment]
nvm I won't cuz I don't know how to even get the color for an address.

**Comment by SoPat712** [comment]
They're all just colored normally now, #675

**Comment by zlshames** [comment]
This was fixed I think. Closing
