### ISSUE TITLE
placeholder text zach/nightly ux option doesnt change anything

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#664]
The option to set the placeholder text as the group or contact name doesn't work at all, it just always says BlueBubbles

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@Intellijence` in `#requests`.

**Comment by SoPat712** [comment]
I'm working on it.

**Comment by SoPat712** [comment]
Ok close this I fixed it

**Comment by SoPat712** [comment]
wait nvm only fixed on material

**Comment by SoPat712** [comment]
nvm fixed on everything

**Comment by cynical89** [comment]
Do you have a commit to relate to this ticket?

**Comment by SoPat712** [comment]
I'm gonna make a pull request for it once I fix the 4 other issues in Material.

**Comment by SoPat712** [comment]
#675

**Comment by zlshames** [comment]
Fixed. Closing
