### ISSUE TITLE
Scroll to bottom on ios Theme isn't shown either

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#671]
see commit 0a846f350a362258a813ac31f3816a33596fb620

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@Intellijence` in `#spam`.

**Comment by CSab6482** [comment]
Is this issue still present?

**Comment by zlshames** [comment]
Fixed. Closing
