### ISSUE TITLE
incoming messages are colored using toColorGradient, should check against database

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#673]
I think it occurs because there is no handle yet for the messages? I'm not particularly sure how the custom coloring that you did works. Whatever that's too difficult for me to figure out. gl @Zlshames

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@Intellijence` in `#spam`.

**Comment by zlshames** [comment]
I definitely check in the database... not sure why. Is this a nightly only thing?

**Comment by SoPat712** [comment]
yes, nightly only, I'm intellijence

**Comment by zlshames** [comment]
I believe this was fixed. Closing
