### ISSUE TITLE
Video scrubber skipped to the end and doesn't scrub properly

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/BlueBubbles-Android-App#674]
https://user-images.githubusercontent.com/53708281/104742189-25351700-5718-11eb-902d-cb37c191b6c6.mp4

I initially found this bug on the nightly, so I switched to the official releases and found the same thing happening there. I'm not sure if it's just this specific video or a problem with the player as a whole.

Further testing shows that it's just this video that has the problem. Here is a link to the video (12 MB, github limits uploads to 10 MB) https://streamable.com/x4f9uo

**Comment by CSab6482** [comment]
I just resent myself this video and all was good, so I'll close this. 0.1.16 rc-1

**Comment by CSab6482** [comment]
> I just resent myself this video and all was good, so I'll close this. 0.1.16 rc-1

I spoke too soon, I just got this bug on 0.1.16 rc-1 with a video of a cat.

https://user-images.githubusercontent.com/53708281/115426634-aea02d80-a1ce-11eb-860a-ca47fe89d8e5.mp4

**Comment by zlshames** [comment]
I believe I fixed this with the v1.0.0 release. Closing unless @CSab6482 reports it still is an issue
