### ISSUE TITLE
Handle .heic images properly

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#676]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#requests`.

**Comment by SoPat712** [comment]
![image](https://user-images.githubusercontent.com/30350506/104855513-4134e600-58db-11eb-8945-6b0231b08ab6.png)

**Comment by tneotia** [comment]
We did this
