### ISSUE TITLE
[Nightly] Replying from notification caused message to fail

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/BlueBubbles-Android-App#683]
I almost never reply from notifications so I don't know if this happens on the stable build too, but here are some pictures and my log with the personal information removed.
![IMG_0288](https://user-images.githubusercontent.com/53708281/105130622-5feed480-5ab5-11eb-8a8b-f0d5a0b94ec2.PNG)
![Screenshot_20210119-224541_Snapchat](https://user-images.githubusercontent.com/53708281/105130627-62512e80-5ab5-11eb-9883-d2fef67599a3.jpg)
![Screenshot_20210119-224638](https://user-images.githubusercontent.com/53708281/105130633-641af200-5ab5-11eb-912b-d03fb1ec77bb.jpg)
[main.txt](https://github.com/BlueBubblesApp/BlueBubbles-Android-App/files/5840301/main.txt)

**Comment by zlshames** [comment]
I dont think this is an issue anymore. Closing
