### ISSUE TITLE
Add toggle for sendin read receipts on Nightly

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#686]
Toggle for sending read receipts similar to typing indicators

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@Clamscrambler` in `#requests`.

**Comment by CSab6482** [comment]
Closed? Or is it open until 0.1.16 is pushed to the PlayStore?

**Comment by CSab6482** [comment]
Is this safe to close?

**Comment by zlshames** [comment]
Closing, this was added
