### ISSUE TITLE
Unfocus keyboard when scrolling up in the chat

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#688]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#requests`.

**Comment by CSab6482** [comment]
This works on Intellijence's latest build

**Comment by SoPat712** [comment]
> This works on Intellijence's latest build

I'm gonna change the implementation to use scroll controller so it only hides on scrolling up, and not when scrolling down.

**Comment by zlshames** [comment]
I implemented this. My branch, beta.
