### ISSUE TITLE
[Nightly] Switching from Material to iOS causes the chat history to disappear

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#691]
A quick fix can be done by exiting and re-entering the app

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#nightly-bugs`.

**Comment by SoPat712** [comment]
ChatBloc.refeshChats():

**Comment by zlshames** [comment]
I dont think this occurs anymore. Closing

**Comment by tneotia** [comment]
Done
