### ISSUE TITLE
Not all symbols are being encoded (`%`)

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#692]
When a password has a `%` in it, the server will fail to decode the password due to an invalid/malformed URI

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#android-bugs`.

**Comment by zlshames** [comment]
This may require coordination with the server. Or at least the server might have to be updated first before implementing this.

**Comment by tneotia** [comment]
This seems to no longer be an issue on nullsafety (I tested using %abc%123).

**Comment by zlshames** [comment]
Yeah I think I fixed it a big ago but never closed cuz I wasn't 100% sure
