### ISSUE TITLE
[Nightly][PrivateAPI] When reacting to a link(with preview), a message showing 'x liked an image' shows up instead of the reaction

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#698]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@Intellijence` in `#nightly-bugs`.

**Comment by CSab6482** [comment]
https://github.com/BlueBubblesApp/BlueBubbles-Android-App/issues/764#issuecomment-786104862

**Comment by zlshames** [comment]
Closing as this is a server ticket: https://github.com/BlueBubblesApp/BlueBubbles-Server/issues/191
