### ISSUE TITLE
Sent location preview is blank at first

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#701]
This issue can be fixed by exiting and re-entering the chat

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#android-bugs`.

**Comment by CSab6482** [comment]
I sent a location yesterday from the latest release candidate, and it kept disappearing/reappearing. The location attachment was always there, I'm just referring to what was inside of it

**Comment by zlshames** [comment]
This was fixed. Closing
