### ISSUE TITLE
iOS 14 Chat Pinning

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#712]
Maybe add a horizontal scroll view to fit 5 or so chats at the top of the screen, long press and hold should open a popupmenu

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@Intellijence` in `#spam`.

**Comment by zlshames** [comment]
The PR needs to be reviewed, as well as modified if there are any conflicts
