### ISSUE TITLE
Sometimes videos play with a green line on the side

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/BlueBubbles-Android-App#713]
I've had this green line appear on both the left and right sides of the video
![green line](https://user-images.githubusercontent.com/53708281/105658925-918ce480-5e95-11eb-9c5a-7dd64b64151e.jpg)
![No green line](https://user-images.githubusercontent.com/53708281/105658927-92257b00-5e95-11eb-9aa3-51e4283dbee6.png)

**Comment by zlshames** [comment]
Strange. And this only happens sometimes?

**Comment by CSab6482** [comment]
> Strange. And this only happens sometimes?

Yes, here is another example I just got today. I'd say it has like a 1/15 incidence
![Screenshot_20210203-215451](https://user-images.githubusercontent.com/53708281/106838620-a70ac700-666a-11eb-9ce5-6c8df2932847.jpg)
![Screenshot_20210203-215507](https://user-images.githubusercontent.com/53708281/106838622-a7a35d80-666a-11eb-95df-eb562184044c.jpg)

**Comment by CSab6482** [comment]
![Screenshot_20210312-174233](https://user-images.githubusercontent.com/53708281/111006226-6d5c6880-835a-11eb-9e7d-13ab3e74580d.jpg)
![Screenshot_20210312-174348](https://user-images.githubusercontent.com/53708281/111006278-87964680-835a-11eb-897a-de376a633d51.jpg)


https://user-images.githubusercontent.com/53708281/111006293-8ebd5480-835a-11eb-8882-90df0e0a9667.mov

**Comment by CSab6482** [comment]
My guess is that this only happens with .MOV files, but I can't verify that. I'll pay more attention the next time I notice it

**Comment by zlshames** [comment]
> My guess is that this only happens with .MOV files, but I can't verify that. I'll pay more attention the next time I notice it

Can you try and confirm this a bit more. If that's the case, then it's ffmpeg kinda screwing up the conversion. Or quite possibly that the totalBytes do not align correctly after converting to an mp4. Not sure

**Comment by CSab6482** [comment]
[Here](https://github.com/jellyfin/jellyfin/issues/3021#issuecomment-647605598) are some [things](https://stackoverflow.com/questions/60778078/ffmpeg-h264-qsv-green-line-at-bottom-of-video) I found on the internet

**Comment by sedlund** [comment]
![image](https://user-images.githubusercontent.com/8109138/112532891-fae28400-8d6e-11eb-8fcb-0398161b5bb5.png)

```
{"Protocol":"File","Id":"ff7b22de5bbef3bf19afdf7f4cc5013b","Path":"C:\12.Angry.Men.1957.1080p.BluRay.x265-RARBG\\12.Angry.Men.1957.1080p.BluRay.x265-RARBG.mp4","Type":"Default","Container":"mov,mp4,m4a,3gp,3g2,mj2","Size":1608809600,"Name":"12.Angry.Men.1957.1080p.BluRay.x265-RARBG","IsRemote":false,"ETag":"76dfa171a07a785708a9e9491cac26ea","RunTimeTicks":57688109056,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"RequiresClosing":false,"RequiresLooping":false,"SupportsProbing":true,"VideoType":"VideoFile","MediaStreams":[{"Codec":"hevc","CodecTag":"hev1","Language":"und","TimeBase":"1/1200000","CodecTimeBase":"1001/24000","VideoRange":"SDR","DisplayTitle":"1080p HEVC","IsInterlaced":false,"BitRate":2000303,"RefFrames":1,"IsDefault":true,"IsForced":false,"Height":1080,"Width":1800,"AverageFrameRate":23.976215,"RealFrameRate":23.976025,"Profile":"Main 10","Type":"Video","AspectRatio":"5:3","Index":0,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"PixelFormat":"yuv420p10le","Level":120},{"Codec":"aac","CodecTag":"mp4a","Language":"eng","TimeBase":"1/48000","CodecTimeBase":"1/48000","DisplayTitle":"Eng AAC mono Default","IsInterlaced":false,"ChannelLayout":"mono","BitRate":224000,"Channels":1,"SampleRate":48000,"IsDefault":true,"IsForced":false,"Profile":"LC","Type":"Audio","Index":1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Level":0}],"MediaAttachments":[],"Formats":[],"Bitrate":2231045,"RequiredHttpHeaders":{}}

C:\Program Files\Jellyfin\Server\ffmpeg.exe -ss 00:00:18.000 -noaccurate_seek -init_hw_device qsv=hw -filter_hw_device hw -i file:"C:\12.Angry.Men.1957.1080p.BluRay.x265-RARBG\12.Angry.Men.1957.1080p.BluRay.x265-RARBG.mp4" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_qsv -preset medium -look_ahead 0 -b:v 8001212 -maxrate 8001212 -bufsize 16002424 -profile:v high -level 4.1  -g 72 -keyint_min 72 -sc_threshold 0 -vf "vpp_qsv=format=nv12" -start_at_zero -vsync -1 -codec:a:0 libmp3lame -ac 1 -ab 224000  -copyts -avoid_negative_ts disabled -f hls -max_delay 5000000 -hls_time 3 -individual_header_trailer 0 -hls_segment_type mpegts -start_number 6 -hls_segment_filename "C:\ProgramData\Jellyfin\Server\transcodes\0ce9cbe7875a9abb5ab488515d42fd23%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "C:\ProgramData\Jellyfin\Server\transcodes\0ce9cbe7875a9abb5ab488515d42fd23.m3u8"


ffmpeg version n4.3.1-1-g4c6eb642fe Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.1.0 (Rev3, Built by MSYS2 project)
  configuration:  --disable-static --enable-shared --cc='ccache gcc' --cxx='ccache g++' --disable-ffplay --disable-debug --enable-gpl --enable-version3 --enable-bzlib --enable-iconv --enable-lzma --enable-zlib --enable-sdl2 --enable-fontconfig --enable-gmp --enable-libass --enable-libzimg --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libwebp --enable-libx264 --enable-libx265 --enable-libdav1d --enable-opencl --enable-dxva2 --enable-d3d11va --enable-amf --enable-libmfx --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvenc --enable-nvdec --enable-ffnvcodec --enable-gnutls --shlibdir=/local64/bin-video
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'file:C:\12.Angry.Men.1957.1080p.BluRay.x265-RARBG\12.Angry.Men.1957.1080p.BluRay.x265-RARBG.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    creation_time   : 2020-04-04T20:47:05.000000Z
    title           : 12.Angry.Men.1957.1080p.BluRay.x265-RARBG
    encoder         : Lavf58.20.100
    comment         : 12.Angry.Men.1957.1080p.BluRay.x265-RARBG
  Duration: 01:36:08.81, start: 0.000000, bitrate: 2231 kb/s
    Stream #0:0(und): Video: hevc (Main 10) (hev1 / 0x31766568), yuv420p10le(tv), 1800x1080 [SAR 1:1 DAR 5:3], 2000 kb/s, 23.98 fps, 23.98 tbr, 1200k tbn, 23.98 tbc (default)
    Metadata:
      creation_time   : 2020-04-04T20:47:05.000000Z
      handler_name    : VideoHandler
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, mono, fltp, 224 kb/s (default)
    Metadata:
      creation_time   : 2020-04-04T20:47:05.000000Z
      handler_name    : SoundHandler
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> h264 (h264_qsv))
  Stream #0:1 -> #0:1 (aac (native) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help
Output #0, hls, to 'C:\ProgramData\Jellyfin\Server\transcodes\0ce9cbe7875a9abb5ab488515d42fd23.m3u8':
  Metadata:
    encoder         : Lavf58.45.100
    Stream #0:0: Video: h264 (h264_qsv), nv12, 1800x1080 [SAR 1:1 DAR 5:3], q=-1--1, 8001 kb/s, 23.98 fps, 90k tbn, 23.98 tbc (default)
    Metadata:
      encoder         : Lavc58.91.100 h264_qsv
    Side data:
      cpb: bitrate max/min/avg: 8001212/0/8001212 buffer size: 16002424 vbv_delay: N/A
    Stream #0:1: Audio: mp3 (libmp3lame), 48000 Hz, mono, fltp, 224 kb/s (default)
    Metadata:
      encoder         : Lavc58.91.100 libmp3lame
```

**Comment by CSab6482** [comment]
This is strange. Both the Michael Stevens video and this video were sent from WebMessage as mp4's that I ripped from YouTube, but in BlueBubbles Android, they were MOV's. I suspect this will happen with all videos that I rip from YouTube, I will test it further, as well as sending the mp4's from BlueBubbles Desktop
![Screenshot_20210401-122033](https://user-images.githubusercontent.com/53708281/113324389-068cf800-92e5-11eb-9e50-3f450b041497.jpg)
![Screenshot_20210401-122246](https://user-images.githubusercontent.com/53708281/113324419-10166000-92e5-11eb-8373-57a5f1863324.jpg)

https://user-images.githubusercontent.com/53708281/113324429-14427d80-92e5-11eb-90f1-04b38f6e4228.mov

**Comment by CSab6482** [comment]
Here is another example. This video, just like the two videos above it, is a YouTube video that I downloaded using the mp4 option from [this website](https://ytmp3.cc/youtube-to-mp3/).
![20210517_212019](https://user-images.githubusercontent.com/53708281/118576149-f1194380-b755-11eb-91c7-81879eacf2da.jpg)
![Screenshot_20210517-212038](https://user-images.githubusercontent.com/53708281/118576147-f1194380-b755-11eb-9c7c-64809b53e4a7.jpg)

https://user-images.githubusercontent.com/53708281/118576111-de067380-b755-11eb-9c67-784f74c2db94.mp4

**Comment by zlshames** [comment]
Related to another ticket. Closing: https://github.com/BlueBubblesApp/BlueBubbles-Android-App/issues/817
