### ISSUE TITLE
[Nightly] It makes you scroll too far to close the keyboard

### ISSUE THREAD

**Issue by SoPat712** [BlueBubblesApp/BlueBubbles-Android-App#725]
it should hide almost instantly when you start scrolling up

on ios theme i just scrolled an entire 5000+ message convo without it hiding
after scrolling to bottom, the scrollController goes completely insane
and it never hides the keyboard again

¯\_(ツ)_/¯

gesture detector implementation just worked better

**Comment by zlshames** [comment]
My branch
