### ISSUE TITLE
[nightly] when you unfocus the keyboard by scrolling up, it doesnt get refocused when you click the scroll to bottom button

### ISSUE THREAD

**Issue by SoPat712** [BlueBubblesApp/BlueBubbles-Android-App#727]

**Comment by zlshames** [comment]
It seems to work fine for me. I have the keyboard open, i scroll up, and it closes. Then i hit scroll to bottom and it scrolls to bottom and re-focuses the keyboard

**Comment by zlshames** [comment]
My branch
