### ISSUE TITLE
Problem syncing read receipts on the latest unofficial Intellijence nightly 1612323021.apk

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#729]
When a read receipt and a delivered receipt are both visible, and then the bottom delivered message is read, the top read receipt disappears, but the bottom tag still appears as delivered until the chat is exited and re-entered

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#nightly-bugs`.

**Comment by CSab6482** [comment]
It appears that delivered tags don't show up if the message was sent from another device (e.g. iPad, not sure if this applies to other BB clients)

**Comment by CSab6482** [comment]
![Screenshot_20210315-163803](https://user-images.githubusercontent.com/53708281/111219093-fd462080-85ad-11eb-8136-cbd3c4d607d4.jpg)
I'm not sure if this screenshot is related, but this happens sometimes too

**Comment by zlshames** [comment]
> ![Screenshot_20210315-163803](https://user-images.githubusercontent.com/53708281/111219093-fd462080-85ad-11eb-8136-cbd3c4d607d4.jpg)
> I'm not sure if this screenshot is related, but this happens sometimes too

No, that is not intentional. I never started redacted mode, so this is a bug. Not sure what it relates to. Maybe the text color is being set to the same color as the bubble for some reason? Have you noticed any patterns with it?

**Comment by CSab6482** [comment]
> > ![Screenshot_20210315-163803](https://user-images.githubusercontent.com/53708281/111219093-fd462080-85ad-11eb-8136-cbd3c4d607d4.jpg)
> > I'm not sure if this screenshot is related, but this happens sometimes too
> 
> No, that is not intentional. I never started redacted mode, so this is a bug. Not sure what it relates to. Maybe the text color is being set to the same color as the bubble for some reason? Have you noticed any patterns with it?

HAHA, I'm sorry for not explaining better. I redacted that on my own and colored in all the personal information. The only bug there is the double read receipts. I was just saying that if redacted mode were to be implemented as an automatic feature, I think that kind of implementation (still showing the bubbles and stuff but coloring them in) would be a good one. Let me know if this makes more sense.

**Comment by CSab6482** [comment]
![Screenshot_20210326-205210](https://user-images.githubusercontent.com/53708281/112706271-98c27580-8e79-11eb-95d2-e8ab77bc7e89.jpg)
![Another One](https://user-images.githubusercontent.com/53708281/112706280-a8da5500-8e79-11eb-9dfe-9a43090743d5.gif)

**Comment by zlshames** [comment]
Closing. I think this is related to https://github.com/BlueBubblesApp/BlueBubbles-Android-App/issues/801
