### ISSUE TITLE
add Google Messages Smart Text Features, such as reminders, attach recent photo, share current location, etc

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#737]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@cdi` in `#requests`.

**Comment by zlshames** [comment]
Reminders Ticket: https://github.com/BlueBubblesApp/BlueBubbles-Android-App/issues/880
Recent Photo Ticket: https://github.com/BlueBubblesApp/BlueBubbles-Android-App/issues/881

Closing as "duplicate" since we extrapolated new tickets from it
