### ISSUE TITLE
viewing an image with reactions while in mini viewer causes grey screen

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#742]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#nightly-bugs`.

**Comment by CSab6482** [comment]
https://user-images.githubusercontent.com/53708281/106843741-c1e23900-6674-11eb-809d-21ca9a118543.mp4
Example video here

**Comment by zlshames** [comment]
I think i fixed this. my beta branch
