### ISSUE TITLE
Tapback/Details menu is bugged while in landscape mode

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#743]
On all messages, the buttons display much larger than they actually are, and on attachments with no caption, the screen goes gray like in issue #742

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#nightly-bugs`.

**Comment by CSab6482** [comment]
![Big Buttons](https://user-images.githubusercontent.com/53708281/106843912-243b3980-6675-11eb-97ee-93670bbcd700.jpg)



![Gray screen](https://user-images.githubusercontent.com/53708281/106843885-138ac380-6675-11eb-9b62-aafe17ebcfed.mp4)

**Comment by zlshames** [comment]
Marking this has Medium-Hard because it will require some UI re-work when in landscape mode

**Comment by CSab6482** [comment]
This is on 1.3.0 beta 4

https://user-images.githubusercontent.com/53708281/129926795-a2d4b25e-da87-4f02-ba8f-2b14fec78155.mp4

**Comment by tneotia** [comment]
I can't reprod

https://user-images.githubusercontent.com/50850142/129928129-e4610fd2-89a0-410d-a0af-80a7f7d37e16.mp4

**Comment by CSab6482** [comment]
Try with the message at the very top, with an attachment, with a long message, or any combination of these

**Comment by tneotia** [comment]
Still doesn't do it for me. Maybe private API needs to be enabled? In which case I can't test it lol

**Comment by CSab6482** [comment]
That's a good point, we could have either Joel or Zach's wife test in that case

**Comment by zlshames** [comment]
> Still doesn't do it for me. Maybe private API needs to be enabled? In which case I can't test it lol

you can enable it even if it doesn't support it. You still get the reaction popup, just sending them doesn’t do anything

**Comment by tneotia** [comment]
Yeah.... then I have to make a custom build and change it so the private API toggle shows up for Big Sur and up..... So much work........ lol I'll try it out in a sec

**Comment by CSab6482** [comment]
I thought Tanay made it so that if the app detects that you are on Big Sur, it doesn't let you toggle the Private API settings on

**Comment by zlshames** [comment]
> I thought Tanay made it so that if the app detects that you are on Big Sur, it doesn't let you toggle the Private API settings on

yeah, but i mean, we can comment that part out temporarily for testing, right?

**Comment by tneotia** [comment]
Fixed with #1381
