### ISSUE TITLE
Tapping a notification when there are multiple notifications from different chats sometimes opens the incorrect chat

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#747]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#android-bugs`.

**Comment by zlshames** [comment]
I need some more info on this. I haven't experienced this, so I'm not sure I can reproduce it. Leaving open for now, but marking as it needs more info

**Comment by CSab6482** [comment]
I think this is safe to close given the new and improved notifications
