### ISSUE TITLE
Fix Youtube Playlist Previews

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#750]
ex: https://youtube.com/playlist?list=PLl-gb0E4MII28GykmtuBXNUNoej-vY5Rz

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#nightly-bugs`.

**Comment by zlshames** [comment]
Fixed. My branch
