### ISSUE TITLE
Fix alignment of timestamps on Material

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#756]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#nightly-bugs`.

**Comment by zlshames** [comment]
Confirmed this is still an issue. The timestamps seemed to be pinned to the relative "top" for incoming messages and the wayyy bottom for outgoing messages
