### ISSUE TITLE
osas script error on removing tapbacks

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#758]
It tells me on terminal, command failed due to execution error because variable undefined is not defined.

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@uprajsinghbk201` in `#nightly-bugs`.

**Comment by zlshames** [comment]
I'm closing this because when an AppleScript is executed instead of the private API call, it means the private API functionality was not setup correctly. Also, if this was an issue, it should be created under the server project
