### ISSUE TITLE
reactions are sent as if responding to an attachment

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#764]
all reactions are sent as if responding to an attachment leading to incorrect notifications for iPhone users when reacting to a non-attachment message

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@Clamscrambler` in `#nightly-bugs`.

**Comment by sgtaziz** [comment]
I'm not sure how helpful this will be, as my experience is from iOS side as opposed to macOS.

When sending a reaction, you are usually passing a `summaryInfo` variable. This variable is what handles showing "Liked an attachment" or "Liked 'Hi!'"

```
// First, you need to enter the string the user is reacting to in the summerInfo "ams" key.
// I am replacing \ufffc with an empty string to remove the unicode character added by attachments.
summaryInfo[@"ams"] = [[textMsg string] stringByReplacingOccurrencesOfString:@"\ufffc" withString:@""];

// You will also need to pass the "amc" key as a boolean. If it is true (or @1), it will react to an attachment.
// If it is false (or @0), it will react to a text message.
summaryInfo[@"amc"] = [summaryInfo[@"ams"] length] == 0 ? @0 : @1;
```

Hope I was able to help!

**Comment by zlshames** [comment]
@sgtaziz the dang invisible attachment character bugs the hell outta me. I remember back in 2020 when i first started BB, it annoyed me so much that they had it. Wasn’t a hard fix, but i end up just stripping it from texts

**Comment by sgtaziz** [comment]
Yeah I'm not sure why the invisible Unicode character even exists. The NSAttributedString is enough to place attachments where needed, but ¯\_(ツ)_/¯

**Comment by CSab6482** [comment]
https://github.com/BlueBubblesApp/BlueBubbles-Android-App/issues/698
Possible dupe

**Comment by zlshames** [comment]
yup. These are all also server issues, so i will move these accordingly. Closing this one once I do

**Comment by zlshames** [comment]
Server ticket: https://github.com/BlueBubblesApp/BlueBubbles-Server/issues/191
