### ISSUE TITLE
Toggle to show avatars in individual chats

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#765]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#requests`.

**Comment by zlshames** [comment]
Make it togglable

**Comment by zlshames** [comment]
This is going to be an option for all chats

**Comment by zlshames** [comment]
This shouldn't be too hard, but it touches a few parts.

1. Add the settings toggle
2. Add the condition to the widget
3. Make sure everything is still aligned correctly
