### ISSUE TITLE
Pinned chats become unpinned randomly

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#772]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#android-bugs`.

**Comment by zlshames** [comment]
Medium-Hard because it's nearly impossible to reproduce for me...

**Comment by zlshames** [comment]
More info:
```
Not sure if it is a known bug but when you mark a chat pinned it loses the pin the next time you receive a message on that chat.

Edit:. Just noticed that the pin is gone when you receive the message in that chat but when you close the app and reopen it is pinned again :thinking:

```

**Comment by zlshames** [comment]
Try this as the workflow to reproduce:
1. Pin a chat
2. Go into the chat
3. Receive a message from that chat
4. Go back to the chat list
5. Should be unpinned?

**Comment by zlshames** [comment]
Fixed. Flutter 2 migration branch
