### ISSUE TITLE
Mark as read via a notification doesnt work (private API, mark as read)

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#776]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#nightly-bugs`.

**Comment by zlshames** [comment]
Whatever code marks the chat as read for the Android App, also needs to invoke the private API call to mark it as read there.

**Comment by tneotia** [comment]
As far as I can tell we have this at notification_manager.dart, conversation_view_mixin, and method_channel_handler.
