### ISSUE TITLE
Make sync indicator yellow instead of red

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#782]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#requests`.

**Comment by zlshames** [comment]
Can't really do this because then we couldnt distinguish between the disconnected status and connecting state. I tried. it didnt work. Closing for now until I learn new info on if maybe this could be something to do
