### ISSUE TITLE
Request to show phone numbers/emails below contact names in the conversation details page

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#784]
to

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#requests`.

**Comment by CSab6482** [comment]
Oh, this didn’t work the way I expected, does the bot behave differently with requests? Here is the original title

Request to show phone numbers/emails below contact names in the conversation details page
![B9318F74-7C97-4525-8A1D-942ECCA7DD50](https://user-images.githubusercontent.com/53708281/108249976-bcc8c380-7123-11eb-8eae-bfcbb5a05c20.jpeg)
![AA89C775-45ED-4280-ACAC-C6EC3AF2A55D](https://user-images.githubusercontent.com/53708281/108249981-bd615a00-7123-11eb-85d4-eb64e014c14b.jpeg)

**Comment by zlshames** [comment]
Done. My beta branch
