### ISSUE TITLE
Request for a Hide/Show More button for the contacts in the conversation details page like on iOS

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#785]
for

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#requests`.

**Comment by CSab6482** [comment]
Original title and description
Request for a Hide/Show More button for the contacts in the conversation details page like on iOS

On iOS the default is to show all the participants, but I feel like having the default as showing five and then having the option to expand the list would be better and make it less scrolling to get to the attachments

**Comment by zlshames** [comment]
@CSab6482 Can you show me how iOS does it?

**Comment by CSab6482** [comment]
> @CSab6482 Can you show me how iOS does it?

Here is an example from a group chat on iOS
![PNG image](https://user-images.githubusercontent.com/53708281/122132603-1f4b7b00-ce09-11eb-8c5f-e74791fed13f.png)
![PNG image 2](https://user-images.githubusercontent.com/53708281/122132605-21153e80-ce09-11eb-9776-803d3843c363.png)
![PNG image 3](https://user-images.githubusercontent.com/53708281/122132607-22466b80-ce09-11eb-9121-70d06d1ce4ee.png)

**Comment by zlshames** [comment]
Your first `easy` issue :)

**Comment by zlshames** [comment]
Done. my beta branch
