### ISSUE TITLE
Sending a text as you're switching from WiFi to data (and possible from data to WiFi) causes the text to duplicate

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#788]
I

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#android-bugs`.

**Comment by CSab6482** [comment]
The original caption said "I've DM'd Zach my logs and will add a picture in the comments", but I messed up my quotation mark placement. Here is the photo
![Bug](https://user-images.githubusercontent.com/53708281/108435502-95532300-7217-11eb-9eb2-0c57ec0ef57c.jpg)

**Comment by zlshames** [comment]
Dupe. Closing
