### ISSUE TITLE
Audio Recording Preview continues to play after exiting.

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#789]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@cdi` in `#android-bugs`.

**Comment by officialcdi** [comment]
https://photos.app.goo.gl/SUNuQFcpbq8V6BrU8

**Comment by zlshames** [comment]
Easy-Medium... Gotta dispose of the audio player... but either re-instate it when the app is re-opened? Or just pause it on exit? not sure yet

**Comment by tneotia** [comment]
Fixed.
