### ISSUE TITLE
Request to have contact photos next to received messages in individual chats like on desktop

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#790]
This could be a toggle in case some people don't want it

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#requests`.

**Comment by tneotia** [comment]
@jjoelj isn't this implemented now?

**Comment by jjoelj** [comment]
> @jjoelj isn't this implemented now?

Yup didn't see this issue and closed the duplicate #1002
