### ISSUE TITLE
Sending a text message with a URL in it turns the whole message into a URL preview that says 'Loading Preview...'

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#797]
For example, 'I'm not sure if it happens with other messages, here's https://duckduckgo.com as an example'

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#android-bugs`.

**Comment by CSab6482** [comment]
![Screenshot_20210223-105026](https://user-images.githubusercontent.com/53708281/108869315-123e1e00-75c5-11eb-9644-74948154ad30.jpg)
^ Picture of how the example message shows up

**Comment by zlshames** [comment]
Duplicate. Closing.
