### ISSUE TITLE
Include message text in the URL Preview Widget

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#798]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#android-bugs`.

**Comment by CSab6482** [comment]
Would issue #797 be closed then?
Here are some example images I sent in the discord
<img width="306" alt="iOS" src="https://user-images.githubusercontent.com/53708281/108871584-4d415100-75c7-11eb-95f0-b8cb70cffaf6.png">
![AirMessage](https://user-images.githubusercontent.com/53708281/108871587-4dd9e780-75c7-11eb-94df-655a60605b31.jpg)
![BlueBubbles](https://user-images.githubusercontent.com/53708281/108871588-4dd9e780-75c7-11eb-8aeb-e4516ff40ac7.jpg)

**Comment by tneotia** [comment]
Done
