### ISSUE TITLE
Make the RegularFileOpener widget respond to taps on the whole widget, not just the type icon

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/BlueBubbles-Android-App#799]
Having Double-Tap Message for Details turned on makes this even more of a challenge

https://user-images.githubusercontent.com/53708281/108916087-c5c20500-75fb-11eb-8ce6-26b616d88bdb.mp4

https://docdro.id/Vh1evLl
^ PDF in question

**Comment by zlshames** [comment]
I can't replicate this. Is this still an issue?

**Comment by CSab6482** [comment]
> I can't replicate this. Is this still an issue?

I found out what the problem was. In the center, there is a square with the letters "PDF" on it, and if I tap that icon, then the file will open without any issues. Can this ticket be turned into a feature request to also have the file open if you tap anywhere in the gray box?

**Comment by zlshames** [comment]
yezzir

**Comment by tneotia** [comment]
Fixed.
