### ISSUE TITLE
Convert all icons for profile pictures to adaptive icons

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#800]
This might be Samsung's fault though idk

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#baffoonery`.

**Comment by CSab6482** [comment]
![Screenshot_20210316-163416_Discord](https://user-images.githubusercontent.com/53708281/111376164-7b212f00-8675-11eb-9c53-c37838c2b110.jpg)
