### ISSUE TITLE
Fix scaling of tap-back icons on larger devices

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#804]
On some phones, like the Galaxy Z Fold 2, the buttons are too small or large in some areas, and they can't be resized

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#android-bugs`.

**Comment by CSab6482** [comment]
![1](https://user-images.githubusercontent.com/53708281/109402812-e0132000-7926-11eb-864c-cf10c90c71ed.jpg)
![2](https://user-images.githubusercontent.com/53708281/109402813-e0abb680-7926-11eb-9a6a-fca43ac0dcba.jpg)
From @Halfway2anywhere in the discord

**Comment by tneotia** [comment]
Also done (it uses the minimum of device height or device width to scale so consistent in landscape or portrait)
