### ISSUE TITLE
Sharing images or attachments is bugged through direct share

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#805]
It causes two copies to be previewed and also sent.

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#android-bugs`.

**Comment by CSab6482** [comment]
![1](https://user-images.githubusercontent.com/53708281/109402848-2b2d3300-7927-11eb-844f-dfabdf938422.jpg)
Red is direct share directly to a chat. green opens search option to find who to send it to; it sends one copy as normal
![2](https://user-images.githubusercontent.com/53708281/109402851-354f3180-7927-11eb-9551-0f2efde83eff.jpg)
This is what I mean in double with the red option.  clicking either "x" discards both copies at the same time
![3](https://user-images.githubusercontent.com/53708281/109402854-426c2080-7927-11eb-9f00-8929ee7f7b5d.jpg)
Sending it actually sends two

From @Blank in the discord

**Comment by CSab6482** [comment]
Is this safe to be closed?

**Comment by zlshames** [comment]
Yup. Closing
