### ISSUE TITLE
Audio Widget has issues loading audio length

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#809]
A newly sent or received audio message shows up as being 0 seconds long, but then when you play it, the seconds add up, and then the app knows and remembers how long the audio message is

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#android-bugs`.

**Comment by tneotia** [comment]
This is no longer an issue with chewie audio
