### ISSUE TITLE
Fix Firebase issue

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#812]
https://stackoverflow.com/questions/60698622/java-io-ioexception-fis-auth-error-in-android-firebase

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#feedback`.

**Comment by zlshames** [comment]
https://firebase.google.com/support/release-notes/android#2020-03-03

**Comment by zlshames** [comment]
I upgraded the package. I think everything is working well now. Closing.
