### ISSUE TITLE
Mute Chat notifications for 1 hour

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#813]
This is mainly for when I'm using iMessage on another device like my iPad or laptop and I have no need to received the notifications on my phone. This could be partially related to issue #693

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#requests`.

**Comment by CSab6482** [comment]
*receive

**Comment by SoPat712** [comment]
So, mute ALL notifications, temporarily? Why not just use do not disturb?

**Comment by CSab6482** [comment]
Yeah you're right. 
![Screenshot_20210319-112055_Snapchat](https://user-images.githubusercontent.com/53708281/111803278-47c4e700-88a5-11eb-89d4-a90a7d15a6f1.jpg)
I also just found out I can do this, which might help. I think this can be closed

**Comment by CSab6482** [comment]
![Screenshot_20210319-140902_YouTube](https://user-images.githubusercontent.com/53708281/111824512-b2cde800-88bc-11eb-8f14-e258a4d74833.jpg)
Here's an update to the situation, something like this Mute 1H button would be perfect

**Comment by zlshames** [comment]
Marking this as hard because you'll need to write some callback code from the Java code to the Dart code
