### ISSUE TITLE
Support Android Auto

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#818]
Check this guide out: https://developer.android.com/training/cars/messaging

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#general`.

**Comment by zlshames** [comment]
This is actually really easy I think. Just read this: https://developer.android.com/training/cars/media/auto

Should be a matter of adding a meta tag

**Comment by romhacks** [comment]
Unfortunately it seems like it's only that simple for media apps (music player, etc). Messaging apps need more stuff and flutter might not support auto as of now. https://github.com/BlueBubblesApp/BlueBubbles-Android-App/issues/1149 is a duplicate of this issue but has some comments referencing this.
