### ISSUE TITLE
Reduce size of connection indicator in Material Theme

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#819]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#android-bugs`.

**Comment by zlshames** [comment]
I think I already reduced it for iOS. Might just need to be reduced on the Material Theme

**Comment by zlshames** [comment]
This was already done. Closing
