### ISSUE TITLE
[Bug] Pound signs cause bugs in files and URLs

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/BlueBubbles-Android-App#826]
The first bug is with a video file that has a pound sign in the file name. The video is unplayable.

https://user-images.githubusercontent.com/53708281/115979506-48136a80-a554-11eb-8774-0806f7552ca3.mp4

The second bug is with URLs that have pound signs, which is similar to [this MyMessage ticket](https://github.com/open-imcore/imcore.react/issues/34)

**Comment by zlshames** [comment]
Just fixed this im pretty sure. Closing.
