### ISSUE TITLE
Voice messages are prompted send/discard twice after recording

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#829]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@Clamscrambler` in `#android-bugs`.

**Comment by zlshames** [comment]
I can't reproduce this. Going to ask in Discord, but otherwise, might close it

**Comment by zlshames** [comment]
Closing this until I either get more info or people get this more anecdotal-y
