### ISSUE TITLE
Videos with the HEVC encoding are not able to send over iMessage (also possible BT.601 error on Catalina)

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/BlueBubbles-Android-App#834]
EDIT - After some testing, Tagavari was able to send a BT.601 video over AirMessage on both 10.13 High Sierra and 11.0 Big Sur. I was able to send the same video over AirMessage on 10.14 Mojave. u/aayyyyyyyyyyyy is not able to send the video through their AirMessage server, which is running on Catalina in a KVM. I am not saying that there is no issue with the BT.601 color profile, but it definitely needs more investigation. In the meantime, I did face quite a few problems with HEVC when performing these tests. Below is my original comment on this issue.

> The BT.709 color profile is supported by iMessage, however. Below is some ffmpeg code that transcodes the unsupported videos to the supported profile.
>
> -c:v libx264 -q:v 5 -c:a copy -ab 192k -ar 44100 -crf 15 -color_primaries bt709 -color_trc bt709 -colorspace bt709
>
> Credit where credit is due, taken from u/aayyyyyyyyyyyy at > https://www.reddit.com/r/AirMessage/comments/n3y1ia/cause_for_why_some_videos_fail_to_send/

**Comment by CSab6482** [comment]
https://github.com/airmessage/airmessage-android/issues/1#issuecomment-831605404

**Comment by zlshames** [comment]
This is actually a server ticket. Re-creating there: https://github.com/BlueBubblesApp/BlueBubbles-Server/issues/189
