### ISSUE TITLE
[0.1.16 rc 3] The in-chat connection indicator intersects with the mark chat as read button if it's enabled

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#849]
electronika originally reported this in <#746560644995612752>, and Sambro99 also sent a photo that showed the graphical bug (though Sambro's photo was to show an issue with the 'Yesterday' text being cut off at the top)

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#android-bugs`.

**Comment by CSab6482** [comment]
The `<#746560644995612752>` in the description is supposed to say `#android-bugs`, it's probably just a Discord embed thing. Below are the screenshots that I was referring to.
![Screenshot_20210515-111830](https://user-images.githubusercontent.com/53708281/118413059-5f350c00-b66b-11eb-903b-8abc26bdf22f.jpg)
![Screenshot_20210516-092400](https://user-images.githubusercontent.com/53708281/118413068-622ffc80-b66b-11eb-8f8a-bc622f9ba8b0.jpg)

**Comment by zlshames** [comment]
Fixed
