### ISSUE TITLE
Some emojis aren't big when they have a skin tone applied to them

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#852]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#android-bugs`.

**Comment by CSab6482** [comment]
![Screenshot_20210524-172203](https://user-images.githubusercontent.com/53708281/120056046-d7a2b200-c007-11eb-8479-ac431f6460e3.jpg)

**Comment by CSab6482** [comment]
Request to reopen. The emoji combination 🤏🕶😳 was small for me on the latest PlayStore release as of June 20, 2021
![Screenshot_20210620-101809](https://user-images.githubusercontent.com/53708281/122677823-026cca00-d1b2-11eb-9baa-831a4083e423.jpg)

**Comment by jjoelj** [comment]
This issue has been fixed
