### ISSUE TITLE
Syncing on 0.1.16 rc5 is... weird

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#854]
Firstly, whenever I do a fresh uninstall and reinstall of BlueBubbles to rc5, it automatically opens to my conversations from 5/19/21 and before (rc5 was compiled on 5/20/21), and I have to reset DB to get to the startup screen. Then, after my set up it doesn't look like it usually does

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#nightly-bugs`.

**Comment by CSab6482** [comment]
Here are some screenshots
![Screenshot_20210526-202424](https://user-images.githubusercontent.com/53708281/120225182-c5489400-c212-11eb-85db-4d866398a356.jpg)
![Screenshot_20210531-131202](https://user-images.githubusercontent.com/53708281/120225195-cbd70b80-c212-11eb-8483-17af0c464dd9.jpg)
Sometimes it stays stuck at 100%, and other times it syncs normally.
![Screenshot_20210526-202517](https://user-images.githubusercontent.com/53708281/120225265-ec06ca80-c212-11eb-81c0-f87c4872b6f2.jpg)
and here's the 5/19/21 thing that I see on first opening the app.

**Comment by zlshames** [comment]
I think I fixed this. Will make a new rc5 for you to test

**Comment by CSab6482** [comment]
I think this should be closed since it's probably due to some kind of back up setting on my phone, not BlueBubbles.

**Comment by zlshames** [comment]
Thanks, closed
