### ISSUE TITLE
[0.1.15 RC 5] Custom Color Text uses black instead of shaded color

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#859]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#feedback`.

**Comment by zlshames** [comment]
I'm not getting this issue. Maybe it's a one-time issue?

**Comment by zlshames** [comment]
I could not replicate this. Closing for now
