### ISSUE TITLE
Custom Hex inputs for theming color picker

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#860]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#requests`.

**Comment by zlshames** [comment]
Marking this as hard, because tbh I don't really know what needs to be done to do this. So some digging/research will need to be had first.

**Comment by tneotia** [comment]
Can't we already specify custom RGB values in the color picker?

**Comment by zlshames** [comment]
> Can't we already specify custom RGB values in the color picker?

Fixed the title

**Comment by tneotia** [comment]
Switch to https://pub.dev/packages/flex_color_picker
