### ISSUE TITLE
Fix grey box issue with the reaction widget when you reacted to the message

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/BlueBubbles-Android-App#873]
Video reference of stack trace: https://discord.com/channels/640229510662455326/746560644995612752/854129106400575518

Screenshot in question: 
![image](https://user-images.githubusercontent.com/18445938/121973856-2eb8be80-cd4c-11eb-877e-738671c47ea5.png)

Should probably also default null handles to `You`?

**Comment by zlshames** [comment]
Reproduce:
1. Have a thread that has 2 messages in it. One with reactions on it from other people. And another with reactions, including yours
2. Tap and hold the message without your reaction to bring up the details
3. Close out of the details and do the same thing to the message that you reacted to

It should show a grey box

**Comment by zlshames** [comment]
Actually the issue might be any time you react to a message. Doesn't matter if you viewed another message details prior

**Comment by CSab6482** [comment]
Is this ticket about the issue in the video below?

https://user-images.githubusercontent.com/53708281/122324399-b6dac780-cef6-11eb-9989-5da4a8dbd0bc.mp4

**Comment by zlshames** [comment]
yes @CSab6482

**Comment by zlshames** [comment]
Fixed. my beta branch
