### ISSUE TITLE
Fix unread messages notification in chat

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/BlueBubbles-Android-App#886]
Below is a screenshot of how it looks on iOS and a video of how it is in BlueBubbles (thanks redacted mode! and @jjoelj)
![PNG image](https://user-images.githubusercontent.com/53708281/122313165-b4bb3d80-cee3-11eb-8eea-21270d296da0.png)

https://user-images.githubusercontent.com/53708281/122313168-b5ec6a80-cee3-11eb-80ff-d5bb256ee5b4.mp4

However, I feel like issue #693 would cause some conflicts with this for private API users. Let me know what you think.

Edit - I got the idea for this ticket from [this comment](https://github.com/BlueBubblesApp/BlueBubbles-Android-App/issues/580#issuecomment-862823207).

**Comment by zlshames** [comment]
@CSab6482 dont we already do this?

**Comment by CSab6482** [comment]
As far as I know, no. In the screenshot/screen recording above, the iOS arrow has a number 3 next to it, but the BlueBubbles arrow is just the arrow.

**Comment by zlshames** [comment]
hmm maybe it broke. Leaving open as a bug

**Comment by tneotia** [comment]
Fixed
