### ISSUE TITLE
color picker text for rgb values should be white, not the primary color

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#897]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#android-bugs`.

**Comment by tneotia** [comment]
This can't be fixed without modifying the source as the `labelTextStyle` doesn't affect the color picker text for some reason :(

**Comment by zlshames** [comment]
I'm unable to replicate this, are you? @tneotia My text is hardcoded to white

**Comment by zlshames** [comment]
But also, you're right in that it can't be fixed without updating the library. I wonder if there is a similar package

**Comment by zlshames** [comment]
Candidate: https://pub.dev/packages/flex_color_picker
