### ISSUE TITLE
Create another menu within message details popup for additional context options

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/BlueBubbles-Android-App#898]
Currently, the message details popup (when you tap and hold a message), provides a context menu for a few actions. Well, we want to add additional actions such as "forward", "start conversation", etc. The only way to do that is to create a different menu with those items. We probably also want to move some of the attachment download options to that other menu as well. This way the context menu stays de-cluttered.

This is marked as medium because it involves UX and deciding the best place to put that menu. I'm leaning towards a floating action menu button that sits either on the left or right side of the screen, depending on which message was selected. When tapped, show the other options.

**Comment by zlshames** [comment]
Marking this as high priority because it will enable us to complete some other tickets

**Comment by tneotia** [comment]
I'm working on this, I was thinking something similar to how iMessage does it:

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-06-19 at 14 29 29](https://user-images.githubusercontent.com/50850142/122652091-dea27900-d10a-11eb-94c4-86c2e95d44fa.png)

After pressing more we could open a dialog of some sort with the list of options. What do you think? I can also implement it the way you suggested, just providing a different idea.

**Comment by zlshames** [comment]
@tneotia I think that's a great idea :)
