### ISSUE TITLE
When a group chat doesn't have a title, don't show the "NAME" field in details

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/BlueBubbles-Android-App#900]

**Comment by tneotia** [comment]
For this, wouldn't you want to show this field so you have the option to name the group if you choose?

Maybe we could have a button saying "ADD NAME" and then show the text field?

**Comment by zlshames** [comment]
@tneotia so I'd say this goes 2 ways. Right now, we can't edit the group name, server side. Though, I wouldn't be against being able to set a custom name to group chats, but just client side on the device (until the server supports it)

**Comment by tneotia** [comment]
@zlshames this can be closed
