### ISSUE TITLE
make attachment downloader animation speed variable depending on chunk size

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#903]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#support`.

**Comment by zlshames** [comment]
Basically, in the CircleProgressBar widget, there is a Duration value that gets set that determines the speed of the progress animation. Right now it's hard coded at 500 milliseconds, however, I think it should scale based on the attachment chunk size. For instance, if the chunk is larger, the animation should be a little slower. If the chunk is super small, the animation can be fast. 

I think it pretty much can match up with the chunk size in kb, directly to the milliseconds for the animation duration. For instance:

500kb chunk -> 500 ms animation

However, I do think the animation should be clamped between 200 ms and 1 second. At least that's my initial impression. If anyone has any input on how to properly do it, please do so

**Comment by zlshames** [comment]
My beta branch. Will merge with development when i got a few more things done
