### ISSUE TITLE
add smooth animation to attachment sender

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#907]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#android-bugs`.

**Comment by zlshames** [comment]
Basically just switch the CircleProgressIndicator widget with the custom CircleProgressBar widget in the attachment sender widget

**Comment by zlshames** [comment]
My beta branch. Will merge with development when i got a few more things done
