### ISSUE TITLE
Handle .tiff images with the unsupported attachment widget

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#912]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@tneot01` in `#support`.

**Comment by tneotia** [comment]
Don't think this is fixable as Android itself doesn't have native support for .tif files, you have to use a 3rd party library

**Comment by zlshames** [comment]
I think it's safe to just display this using the unsupported attachment widget. Then we can use android's OpenIntents to try and find and open it in a supported app
