### ISSUE TITLE
Implement attachment downloader queue

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#917]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#community-contributions`.

**Comment by zlshames** [comment]
This will ensure only a set number of downloads can occur at once (everything else is queued). If a ton of attachments are being downloaded at once, it can and will slow down your phone as well as drain battery

**Comment by zlshames** [comment]
I think we can extend our `queue_manager.dart` class and add support for threading and processing multiple items at one time, given a max
