### ISSUE TITLE
Fix share target issue when sharing a contact (vcard)

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#918]
the

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#android-development`.

**Comment by zlshames** [comment]
This might just be a matter of adding an additional supported MIME type

**Comment by zlshames** [comment]
I was unable to replicate this bug. Was only able to one time on another device. If it happens again, I will re-open
