### ISSUE TITLE
Read recipes still don't show correctly

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#939]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#community-contributions`.

**Comment by zlshames** [comment]
I believe an easy way to test this is first, send a message from BB. Then, staying in the chat, go to your mac and send a message from there. The new message should popup, but without a read receipt

**Comment by tneotia** [comment]
Backing out and re-entering shows the read receipt, seems related to #965

**Comment by tneotia** [comment]
This seems like a much bigger issue than a UI issue as the message marker class doesn't even get an updated read receipt. How do we handle read receipts? Is the server supposed to send down the message again with an updated read receipt?

**Comment by zlshames** [comment]
> This seems like a much bigger issue than a UI issue as the message marker class doesn't even get an updated read receipt. How do we handle read receipts? Is the server supposed to send down the message again with an updated read receipt?

There is one issue I noticed, but couldn't figure it out for the short time I looked at it. If you go into a chat, and then scroll up a handful of times, you will notice a StreamSubscription error pop up in the logs. It's for the MessageMarkers stream. I’m not sure what's causing it, or how to fix it, but i wonder if that has anything to do with it.

**Comment by zlshames** [comment]
The reason I know this isn't a server issue is because leaving and re-entering the chat pretty much 100% fixes it and the read receipts are shown correctly.
