### ISSUE TITLE
[GetX Migration] Migrate all snackbars

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#942]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#community-contributions`.

**Comment by tneotia** [comment]
Get.rawSnackbar will behave like our current inplementation

**Comment by zlshames** [comment]
I migrated to the new snackbar. New style too, which I like a LOT better. Changes are now in development branch
