### ISSUE TITLE
[GetX Migration] Migrate settings

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#944]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#community-contributions`.

**Comment by zlshames** [comment]
This will involve turning our settings options into observables so that our UI can react easily to settings changes.

**Comment by zlshames** [comment]
Marking this as high priority, because making settings observable would make new toggles/options super easy to implement

**Comment by tneotia** [comment]
Done
