### ISSUE TITLE
[GetX Migration] Migrate all isEmpty checks to use GetUtils.isNullorBlank

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#947]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#community-contributions`.

**Comment by tneotia** [comment]
We shouldn't do this because this is removed in nullsafety fyi

**Comment by zlshames** [comment]
Instead of replacing all uses of Utils.isNullOrEmpty, I instead just added the call to GetUtils.isNullOrBlank to the end of that method so it's combined essentially. Works perfect.
