### ISSUE TITLE
[GetX Migration] Migrate all URL regex with GetUtils.isURL

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#948]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#community-contributions`.

**Comment by zlshames** [comment]
@tneotia I’m not sure if you did this already, but since @jjoelj was assigned, make sure you either re-assign or let him know you're taking it on so you don’t dupe work. Good work overall though
