### ISSUE TITLE
Initialize camera preview in a post frame callback to reduce lag when opening the share menu

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#963]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#support`.

**Comment by zlshames** [comment]
Adding high priority only because i think this could be an easy but good reward UX wise for users

**Comment by tneotia** [comment]
@jjoelj I finished this one up, it doesn't seem very laggy anymore even in debug which is great.
