### ISSUE TITLE
ignore syncing any chats starting with 'urn:biz' for the chat identifier/guid

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#969]
whichever gets printed into the setup console

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#support`.

**Comment by zlshames** [comment]
This is what is causing a sync issue:

![image](https://user-images.githubusercontent.com/18445938/123516379-c9c56880-d669-11eb-9334-f7eb0b427fce.png)
