### ISSUE TITLE
Fade in from splash screen to ease the transition

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#978]
I think this can be done by replicating the splash screen as a full screen widget that fade transitions to the chat list. This may even be good because it may mask the chats initially loading in

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#support`.

**Comment by tneotia** [comment]
See https://github.com/flutter/flutter/issues/63156#issuecomment-670390702, maybe this can be used in reverse to enable the fade in

**Comment by tneotia** [comment]
Should be fixed now
