### ISSUE TITLE
Show other socket status updates in setup log

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#983]
Currently, we only show disconnected. So if you disconnect, and reconnect, the logs will not tell the user that they reconnected and it may cause confusion

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#support`.

**Comment by zlshames** [comment]
We may even want to create a method to "wait" for the status to change back to connected. So if a disconnect occurs, the setup sync function can wait until the socket is reconnected, and resume

**Comment by zlshames** [comment]
DIdn't do what i said in the comment above, however, i added a connected status as part of the log
