### ISSUE TITLE
[Unreleased] Socket disconnect toast seems to show even when you're connected

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/BlueBubbles-Android-App#997]

**Comment by tneotia** [comment]
Maybe related to the timer fix I had implemented? Don't know if that is working correctly...

**Comment by zlshames** [comment]
This is easily replicated by having the app open, then opening the switcher, then re-entering the app

**Comment by tneotia** [comment]
Done in nullsafety branch
